#!/usr/bin/env python3
"""
HorusOps | Interactive CLI Setup Wizard
A zero-dependency, pure terminal configuration engine for HorusOps:
- 100% CLI and Terminal Native (No web server, no browser, zero port overhead).
- Bilingual support: Arabic and English.
- Validates Telegram Bot, Groq AI, and GitHub credentials live.
- Auto-detects Telegram Chat ID from incoming messages.
- Scans and auto-discovers Git repositories and dev server processes.
- Writes .env, servers.json, targets.json, and prompts/*.txt securely.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import ssl
import subprocess
import sys
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parent
ENV_FILE = ROOT_DIR / ".env"
SERVERS_FILE = ROOT_DIR / "servers.json"
TARGETS_FILE = ROOT_DIR / "targets.json"
CONFIG_FILE = ROOT_DIR / "config.toml"
PROMPTS_DIR = ROOT_DIR / "prompts"

DEFAULT_PROMPTS = {
    "manager_report": (
        "أنت مستشار تنفيذي تقني. المطلوب كتابة تقرير إنجاز يومي موجه لمدير غير تقني يغطي دورة العمل: {shift_label}.\n"
        "شروط صارمة:\n"
        "1. ممنوع تماماً استخدام مصطلحات برمجية جافة (لا تذكر git, commit, branch, diff, hash, terminal).\n"
        "2. اكتب باختصار شديد وبشكل عملي: لخص ما تم إنجازه بنقاط واضحة (تحسينات الواجهة، إضافة ميزات، معالجة أخطاء، تجهيز بيئة العمل).\n"
        "3. التنسيق:\n"
        "[REPORT] تقرير إنجاز الأعمال اليومية\n"
        "• دورة العمل: {shift_label}\n"
        "• ملخص تنفيذي: سطر واحد موجز يوضح تقدم العمل.\n"
        "• المشاريع المنجزة: اسم المشروع وتحته نقطتان أو ثلاث توضح الأعمال المكتملة بلغة الأعمال.\n"
        "• الحالة: جاهز للمراجعة / قيد العمل."
    ),
    "diagnose": (
        "أنت محرك تشخيص أخطاء تقني (Diagnostic Engine) متخصص في هندسة النظم والـ DevOps.\n"
        "ردك تقني، مباشر، موجز، وخالٍ تماماً من أي إيموجيز أو مقدمات أو عبارات ترحيبية.\n"
        "حلل السجلات المرفقة، حدد السبب الجذري للخطأ (Root Cause)، واقترح الحل العملي المباشر في نقاط محددة."
    ),
    "chat": (
        "أنت محرك تحليل واستعلامات تشغيلي لنظام HorusOps.\n"
        "قواعد صارمة لأسلوب الرد:\n"
        "1. كن رسمياً، مهنياً، ومقتضباً إلى أقصى حد ممكن دون الإخلال بالمعلومة.\n"
        "2. ادخل في صلب الإجابة مباشرة بنقاط محددة، أرقام دقيقة، ومسارات صريحة.\n"
        "3. ممنوع تماماً أي عبارات ترحيبية، مجاملات، مقدمات، أو مشاعر.\n"
        "4. اعتمد فقط على بيانات المشاريع الحقيقية المرفقة في السياق بدقة تامة.\n"
        "5. راعِ سياق الرسائل السابقة المرفقة في التاريخ للإجابة دون طلب توضيح."
    ),
}


def read_prompts() -> dict[str, str]:
    prompts = {}
    for k, default_text in DEFAULT_PROMPTS.items():
        p_file = PROMPTS_DIR / f"{k}.txt"
        if p_file.is_file():
            try:
                prompts[k] = p_file.read_text(encoding="utf-8").strip()
                continue
            except Exception:
                pass
        prompts[k] = default_text
    return prompts


def write_prompts(prompts: dict[str, str]) -> None:
    PROMPTS_DIR.mkdir(parents=True, exist_ok=True)
    for k, text in prompts.items():
        if k in DEFAULT_PROMPTS and isinstance(text, str):
            p_file = PROMPTS_DIR / f"{k}.txt"
            p_file.write_text(text.strip(), encoding="utf-8")


def read_json_safe(path: Path, default_val: dict) -> dict:
    if path.is_file():
        try:
            with open(path, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception:
            pass
    return default_val


def parse_env_file(path: Path) -> dict[str, str]:
    data: dict[str, str] = {}
    if path.is_file():
        try:
            for line in path.read_text(encoding="utf-8").splitlines():
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, v = line.split("=", 1)
                    data[k.strip()] = v.strip().strip("'\"")
        except Exception:
            pass
    return data


def write_env_file(path: Path, env_data: dict[str, str]) -> None:
    lines = [
        "# ====================================================================",
        "# HorusOps / git-auto-sync Environment Configuration",
        "# Generated by HorusOps CLI Setup Wizard",
        "# ====================================================================",
        "",
        "# --- Telegram Bot Configuration ---",
        f'TELEGRAM_BOT_TOKEN="{env_data.get("TELEGRAM_BOT_TOKEN", "")}"',
        f'TELEGRAM_CHAT_ID="{env_data.get("TELEGRAM_CHAT_ID", "")}"',
        f'TELEGRAM_ADMIN_IDS="{env_data.get("TELEGRAM_ADMIN_IDS", env_data.get("TELEGRAM_CHAT_ID", ""))}"',
        "",
        "# --- AI & Diagnostic Engine (Groq) ---",
        f'GROQ_API_KEY="{env_data.get("GROQ_API_KEY", "")}"',
        f'GROQ_MODEL="{env_data.get("GROQ_MODEL", "llama-3.3-70b-versatile")}"',
        "",
        "# --- GitHub Integration ---",
        f'GITHUB_TOKEN="{env_data.get("GITHUB_TOKEN", "")}"',
        "",
        "# --- Git Auto Sync Settings ---",
        f'SYNC_BASE_DIR="{env_data.get("SYNC_BASE_DIR", "~/projects")}"',
        f'SYNC_IGNORED_NAMES="{env_data.get("SYNC_IGNORED_NAMES", "ignore,personal,archive,.git,node_modules,dist,build,.venv")}"',
        f'SYNC_PUSH="{env_data.get("SYNC_PUSH", "true")}"',
        f'SYNC_INTERVAL_MINUTES="{env_data.get("SYNC_INTERVAL_MINUTES", "30")}"',
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")
    try:
        os.chmod(str(path), 0o600)
    except Exception:
        pass


def safe_urlopen(req: urllib.request.Request, timeout: int = 10):
    try:
        return urllib.request.urlopen(req, timeout=timeout)
    except urllib.error.URLError as e:
        if "CERTIFICATE_VERIFY_FAILED" in str(e):
            ctx = ssl._create_unverified_context()
            return urllib.request.urlopen(req, timeout=timeout, context=ctx)
        raise


def test_telegram_token(token: str) -> dict:
    if not token:
        return {"ok": False, "error": "Token is empty."}
    url = f"https://api.telegram.org/bot{token}/getMe"
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "HorusOps-CLI/1.0"})
        with safe_urlopen(req, timeout=10) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            if data.get("ok"):
                user = data.get("result", {})
                return {
                    "ok": True,
                    "name": user.get("first_name", ""),
                    "username": user.get("username", ""),
                    "id": user.get("id"),
                }
            return {"ok": False, "error": data.get("description", "Unknown error")}
    except urllib.error.HTTPError as exc:
        try:
            d = json.loads(exc.read().decode("utf-8", errors="ignore"))
            return {"ok": False, "error": d.get("description", f"HTTP {exc.code}")}
        except Exception:
            return {"ok": False, "error": f"HTTP {exc.code}: {exc.reason}"}
    except Exception as exc:
        return {"ok": False, "error": str(exc)}


def detect_telegram_chat_id(token: str) -> dict:
    if not token:
        return {"ok": False, "error": "Token is required."}
    url = f"https://api.telegram.org/bot{token}/getUpdates?limit=20&offset=-10"
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "HorusOps-CLI/1.0"})
        with safe_urlopen(req, timeout=10) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            if not data.get("ok"):
                return {"ok": False, "error": data.get("description", "Unknown error")}
            updates = data.get("result", [])
            if not updates:
                return {
                    "ok": False,
                    "error": "No incoming messages detected yet. Send any message (e.g. /start) to your bot on Telegram and retry.",
                }
            for item in reversed(updates):
                msg = item.get("message") or item.get("edited_message") or item.get("channel_post") or item.get("callback_query", {}).get("message")
                from_u = (item.get("message") or item.get("callback_query", {})).get("from", {})
                chat = msg.get("chat", {}) if msg else {}
                chat_id = from_u.get("id") or chat.get("id")
                if chat_id:
                    return {
                        "ok": True,
                        "chat_id": str(chat_id),
                        "name": from_u.get("first_name", "") or chat.get("title", ""),
                        "username": from_u.get("username", "") or chat.get("username", ""),
                    }
            return {
                "ok": False,
                "error": "Could not parse a valid user ID from recent messages.",
            }
    except urllib.error.HTTPError as exc:
        try:
            d = json.loads(exc.read().decode("utf-8", errors="ignore"))
            return {"ok": False, "error": d.get("description", f"HTTP {exc.code}")}
        except Exception:
            return {"ok": False, "error": f"HTTP {exc.code}: {exc.reason}"}
    except Exception as exc:
        return {"ok": False, "error": str(exc)}


def test_groq_key(key: str) -> dict:
    if not key:
        return {"ok": False, "error": "Groq API key is empty."}
    url = "https://api.groq.com/openai/v1/models"
    try:
        req = urllib.request.Request(
            url,
            headers={
                "Authorization": f"Bearer {key}",
                "User-Agent": "HorusOps-CLI/1.0",
            },
        )
        with safe_urlopen(req, timeout=10) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            models = [m.get("id") for m in data.get("data", []) if m.get("id")]
            return {"ok": True, "models_count": len(models), "models": models[:6]}
    except urllib.error.HTTPError as exc:
        try:
            d = json.loads(exc.read().decode("utf-8", errors="ignore"))
            msg = d.get("error", {}).get("message") or d.get("description")
            return {"ok": False, "error": msg or f"HTTP {exc.code}"}
        except Exception:
            return {"ok": False, "error": f"HTTP {exc.code}: {exc.reason}"}
    except Exception as exc:
        return {"ok": False, "error": str(exc)}


def test_github_token(token: str) -> dict:
    if not token:
        return {"ok": False, "error": "GitHub token is empty."}
    url = "https://api.github.com/user"
    try:
        req = urllib.request.Request(
            url,
            headers={
                "Authorization": f"token {token}",
                "User-Agent": "HorusOps-CLI/1.0",
                "Accept": "application/vnd.github.v3+json",
            },
        )
        with safe_urlopen(req, timeout=10) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            return {
                "ok": True,
                "login": data.get("login", ""),
                "name": data.get("name", ""),
            }
    except urllib.error.HTTPError as exc:
        try:
            d = json.loads(exc.read().decode("utf-8", errors="ignore"))
            return {"ok": False, "error": d.get("message", f"HTTP {exc.code}")}
        except Exception:
            return {"ok": False, "error": f"HTTP {exc.code}: {exc.reason}"}
    except Exception as exc:
        return {"ok": False, "error": str(exc)}


def get_repo_branch(repo_path: Path) -> str:
    head = repo_path / ".git" / "HEAD"
    if head.is_file():
        try:
            c = head.read_text().strip()
            if c.startswith("ref: refs/heads/"):
                return c.split("refs/heads/")[1]
        except Exception:
            pass
    return "main"


def scan_repositories_in_paths(paths: list[str]) -> list[dict]:
    repos = []
    seen = set()
    ignored = {"ignore", "personal", "archive", "node_modules", ".venv", "dist", "build", ".git"}
    for p_str in paths:
        if not p_str or not p_str.strip():
            continue
        p = Path(p_str.strip()).expanduser()
        if not p.is_dir():
            continue
        p_res = p.resolve()
        if (p_res / ".git").exists():
            r_str = str(p_res)
            if r_str not in seen:
                seen.add(r_str)
                repos.append({"name": p_res.name, "path": r_str, "branch": get_repo_branch(p_res)})
        try:
            for item in sorted(p_res.iterdir()):
                if item.is_dir() and item.name not in ignored and (item / ".git").exists():
                    r_str = str(item.resolve())
                    if r_str not in seen:
                        seen.add(r_str)
                        repos.append({"name": item.name, "path": r_str, "branch": get_repo_branch(item)})
        except Exception:
            pass
    return repos


def auto_scan_servers_in_paths(paths: list[str]) -> dict:
    repos = scan_repositories_in_paths(paths)
    servers = {}
    used_ports = set()

    for r in repos:
        r_path = Path(r["path"])
        name = r["name"]
        srv_key = re.sub(r"[^a-zA-Z0-9_]", "_", name.lower()).strip("_") or "srv"

        # 1. Node / JS
        pkg_file = r_path / "package.json"
        if pkg_file.is_file():
            try:
                pkg_data = json.loads(pkg_file.read_text(encoding="utf-8"))
                deps = {**pkg_data.get("dependencies", {}), **pkg_data.get("devDependencies", {})}
                scripts = pkg_data.get("scripts", {})
                port = 3000
                while port in used_ports:
                    port += 1
                used_ports.add(port)

                cmd = "npm run dev" if "dev" in scripts else ("npm start" if "start" in scripts else "node index.js")
                tech = "Node.js"
                if "next" in deps:
                    tech = "Next.js"
                elif "vite" in deps:
                    tech = "Vite"
                    port = 5173 if 5173 not in used_ports else port
                elif "react-scripts" in deps:
                    tech = "React"

                servers[srv_key] = {
                    "name": f"{name} ({tech})",
                    "cwd": str(r_path),
                    "cmd": cmd,
                    "port": port,
                    "aliases": [name.lower(), srv_key],
                }
                continue
            except Exception:
                pass

        # 2. Django
        if (r_path / "manage.py").is_file():
            port = 8000
            while port in used_ports:
                port += 1
            used_ports.add(port)
            servers[srv_key] = {
                "name": f"{name} (Django)",
                "cwd": str(r_path),
                "cmd": f"python3 manage.py runserver 0.0.0.0:{port}",
                "port": port,
                "aliases": [name.lower(), srv_key],
            }
            continue

        # 3. FastAPI / Flask / Python
        if (r_path / "main.py").is_file() or (r_path / "app.py").is_file():
            port = 8000
            while port in used_ports:
                port += 1
            used_ports.add(port)
            main_text = ""
            try:
                if (r_path / "main.py").is_file():
                    main_text = (r_path / "main.py").read_text(encoding="utf-8", errors="ignore")
                elif (r_path / "app.py").is_file():
                    main_text = (r_path / "app.py").read_text(encoding="utf-8", errors="ignore")
            except Exception:
                pass

            if "FastAPI" in main_text or "fastapi" in main_text:
                cmd = f"uvicorn main:app --port {port} --reload"
                tech = "FastAPI"
            elif "Flask" in main_text or "flask" in main_text:
                cmd = f"flask run --port {port}"
                tech = "Flask"
                port = 5000 if 5000 not in used_ports else port
            else:
                cmd = "python3 main.py" if (r_path / "main.py").is_file() else "python3 app.py"
                tech = "Python"

            servers[srv_key] = {
                "name": f"{name} ({tech})",
                "cwd": str(r_path),
                "cmd": cmd,
                "port": port,
                "aliases": [name.lower(), srv_key],
            }

    return servers


def run_interactive_wizard():
    print("=" * 68)
    print(" [HORUS-OPS] Autonomous DevOps & Server Orchestration Platform")
    print(" Interactive Terminal Configuration Wizard")
    print("=" * 68)

    # Language selection
    print("Select Language / اختر لغة الإعداد:")
    print("  [1] العربية (الافتراضية)")
    print("  [2] English")
    lang_choice = input("Option / الاختيار [1]: ").strip()
    is_ar = lang_choice != "2"

    print("-" * 68)
    if is_ar:
        print("ملاحظة: اضغط Enter للموافقة على القيمة الافتراضية المعروضة بين أقواس [].\n")
    else:
        print("Note: Press Enter to accept the default value shown in brackets [].\n")

    current_env = parse_env_file(ENV_FILE)

    # 1. Telegram Bot Token
    def_token = current_env.get("TELEGRAM_BOT_TOKEN", "")
    if is_ar:
        label = f"1. توكن بوت تيليجرام (Telegram Bot Token) [{def_token[:10]}...]: " if def_token else "1. توكن بوت تيليجرام (Telegram Bot Token): "
    else:
        label = f"1. Telegram Bot Token [{def_token[:10]}...]: " if def_token else "1. Telegram Bot Token: "

    token = input(label).strip() or def_token
    while not token:
        msg = "[!] توكن البوت إلزامي. أنشئ بوتاً عبر @BotFather في تيليجرام وأدخل التوكن:" if is_ar else "[!] Bot token is required. Create a bot via @BotFather and enter token:"
        print(msg)
        token = input("Token: ").strip()

    print("   [*] Verifying bot token with Telegram API..." if not is_ar else "   [*] جاري التحقق من التوكن عبر Telegram API...")
    tg_test = test_telegram_token(token)
    if tg_test.get("ok"):
        print(f"   [OK] Verified: {tg_test.get('name')} (@{tg_test.get('username')})")
    else:
        print(f"   [WARN] {tg_test.get('error')}")

    # 2. Telegram User ID / Chat ID
    def_user_id = current_env.get("TELEGRAM_ADMIN_IDS", "") or current_env.get("TELEGRAM_CHAT_ID", "")
    if is_ar:
        print("\n2. معرّف تيليجرام الرقمي (Telegram User/Chat ID):")
        print("   - يمكنك إرسال أي رسالة لبوتك على تيليجرام (مثل /start) لالتقاط المعرف تلقائياً.")
        print("   - أو إدخال المعرف مباشرة إذا كنت تعرفه.")
        prompt_uid = f"   أدخل المعرف أو اضغط Enter للالتقاط التلقائي [{def_user_id}]: "
    else:
        print("\n2. Telegram Numerical User/Chat ID:")
        print("   - Send any message (e.g. /start) to your bot on Telegram for auto-detection.")
        print("   - Or enter your numerical user ID directly.")
        prompt_uid = f"   Enter User ID or press Enter for auto-detect [{def_user_id}]: "

    uid_input = input(prompt_uid).strip()

    if uid_input:
        user_id = uid_input
    else:
        # User pressed Enter: attempt live auto-detection
        print("   [*] Polling incoming updates..." if not is_ar else "   [*] جاري فحص الرسائل الواردة للبوت لالتقاط المعرف...")
        det = detect_telegram_chat_id(token)
        if det.get("ok"):
            user_id = det["chat_id"]
            print(f"   [OK] Auto-detected User ID: {user_id} ({det.get('name')})")
        elif def_user_id and def_user_id != "123456789":
            user_id = def_user_id
            print(f"   [INFO] Retained existing User ID: {user_id}")
        else:
            print(f"   [WARN] {det.get('error')}")
            user_id = input("   Enter User ID manually / أدخل المعرف يدوياً: ").strip()

    # 3. Base Directory
    default_base = current_env.get("SYNC_BASE_DIR", str(Path.home() / "projects"))
    if is_ar:
        print(f"\n3. مسار مجلد المشاريع (Projects Base Directory) [{default_base}]:")
        prompt_base = "   المسار (يدعم مسارات متعددة مفصولة بفاصلة): "
    else:
        print(f"\n3. Projects Base Directory [{default_base}]:")
        prompt_base = "   Path (comma-separated for multiple roots): "

    base_dir_in = input(prompt_base).strip() or default_base
    paths = [p.strip() for p in base_dir_in.split(",") if p.strip()]

    print("   [*] Scanning repositories..." if not is_ar else "   [*] جاري فحص واكتشاف مستودعات Git...")
    found_repos = scan_repositories_in_paths(paths)
    if is_ar:
        print(f"   [OK] تم العثور على {len(found_repos)} مستودع Git.")
    else:
        print(f"   [OK] Discovered {len(found_repos)} Git repositories.")
    for r in found_repos[:5]:
        print(f"      - {r['name']} (branch: {r['branch']})")
    if len(found_repos) > 5:
        print(f"      ... and {len(found_repos) - 5} more.")

    # 4. Groq API Key
    def_groq = current_env.get("GROQ_API_KEY", "")
    if is_ar:
        print(f"\n4. مفتاح Groq API لتشخيص الأعطال والتقارير الذكية (اختياري) [{def_groq[:8]}...]:" if def_groq else "\n4. مفتاح Groq API لتشخيص الأعطال والتقارير الذكية (اختياري):")
        prompt_groq = "   المفتاح (اضغط Enter للتخطي): "
    else:
        print(f"\n4. Groq API Key for AI incident diagnostics (optional) [{def_groq[:8]}...]:" if def_groq else "\n4. Groq API Key for AI incident diagnostics (optional):")
        prompt_groq = "   Key (press Enter to skip): "

    groq_key = input(prompt_groq).strip() or def_groq
    if groq_key:
        print("   [*] Testing Groq API key..." if not is_ar else "   [*] التحقق من صلاحية مفتاح Groq...")
        g_test = test_groq_key(groq_key)
        if g_test.get("ok"):
            print(f"   [OK] Groq API valid. Models available: {g_test.get('models_count')}")
        else:
            print(f"   [WARN] {g_test.get('error')}")

    # 5. GitHub Token
    def_gh = current_env.get("GITHUB_TOKEN", "")
    if is_ar:
        print(f"\n5. توكن GitHub الشخصي لمهام البناء و CI/CD (اختياري) [{def_gh[:8]}...]:" if def_gh else "\n5. توكن GitHub الشخصي لمهام البناء و CI/CD (اختياري):")
        prompt_gh = "   التوكن (اضغط Enter للتخطي): "
    else:
        print(f"\n5. GitHub Personal Access Token for CI/CD (optional) [{def_gh[:8]}...]:" if def_gh else "\n5. GitHub Personal Access Token for CI/CD (optional):")
        prompt_gh = "   Token (press Enter to skip): "

    gh_token = input(prompt_gh).strip() or def_gh
    if gh_token:
        print("   [*] Testing GitHub token..." if not is_ar else "   [*] التحقق من توكن GitHub...")
        gh_test = test_github_token(gh_token)
        if gh_test.get("ok"):
            print(f"   [OK] GitHub authenticated as: @{gh_test.get('login')}")
        else:
            print(f"   [WARN] {gh_test.get('error')}")

    # 6. Auto-discover Servers
    print("\n[*] Discovering local servers and runtimes..." if not is_ar else "\n[*] فحص المشاريع واكتشاف الخوادم المحلية وتوليد servers.json...")
    auto_servers = auto_scan_servers_in_paths(paths)
    existing_servers = read_json_safe(SERVERS_FILE, {}).get("servers", {})
    merged_servers = {**auto_servers, **existing_servers}
    if is_ar:
        print(f"   [OK] تم تجهيز وتعريف {len(merged_servers)} خادم(ات) في servers.json.")
    else:
        print(f"   [OK] Configured {len(merged_servers)} server definition(s) in servers.json.")
    for s_id, s_info in list(merged_servers.items())[:5]:
        print(f"      [{s_id}] {s_info.get('name')} -> Port: {s_info.get('port')} (cmd: {s_info.get('cmd')})")

    # 7. Write Configurations
    new_env = {
        "TELEGRAM_BOT_TOKEN": token,
        "TELEGRAM_USER_ID": user_id,
        "TELEGRAM_CHAT_ID": user_id,
        "TELEGRAM_ADMIN_IDS": user_id,
        "GROQ_API_KEY": groq_key,
        "GROQ_MODEL": current_env.get("GROQ_MODEL", "llama-3.3-70b-versatile"),
        "GITHUB_TOKEN": gh_token,
        "SYNC_BASE_DIR": base_dir_in,
        "SYNC_IGNORED_NAMES": current_env.get("SYNC_IGNORED_NAMES", "ignore,personal,archive,.git,node_modules,dist,build,.venv"),
        "SYNC_PUSH": current_env.get("SYNC_PUSH", "true"),
        "SYNC_INTERVAL_MINUTES": current_env.get("SYNC_INTERVAL_MINUTES", "30"),
    }
    write_env_file(ENV_FILE, new_env)

    with open(SERVERS_FILE, "w", encoding="utf-8") as f:
        json.dump({"servers": merged_servers}, f, ensure_ascii=False, indent=2)

    if not TARGETS_FILE.exists():
        example_targets = read_json_safe(ROOT_DIR / "targets.example.json", {"targets": {}})
        with open(TARGETS_FILE, "w", encoding="utf-8") as f:
            json.dump(example_targets, f, ensure_ascii=False, indent=2)

    # Ensure default prompts exist
    write_prompts(read_prompts())

    print("\n" + "=" * 68)
    if is_ar:
        print(" [OK] تم حفظ جميع الإعدادات بنجاح في:")
        print("   - .env (بيانات الاعتماد المشفرة محلياً)")
        print("   - servers.json (تعريفات الخوادم المحلية)")
        print("   - targets.json (أهداف البناء CI/CD)")
        print("   - prompts/ (موجهات الذكاء الاصطناعي)")
        print("=" * 68)
        print("\nالخطوة التالية - لتشغيل النظام:")
        print("   ./scripts/run_bot.sh          # تشغيل مباشر للبوت في الطرفية")
        print("   ./scripts/install_launchd.sh  # تشغيل كخدمة خلفية دائمة على macOS")
        print("   ./scripts/install_systemd.sh  # تشغيل كخدمة خلفية دائمة على Linux\n")
    else:
        print(" [OK] Configuration saved successfully:")
        print("   - .env (Encrypted local credentials)")
        print("   - servers.json (Monitored server processes)")
        print("   - targets.json (CI/CD pipeline targets)")
        print("   - prompts/ (Modular AI system prompts)")
        print("=" * 68)
        print("\nNext steps to launch HorusOps:")
        print("   ./scripts/run_bot.sh          # Run bot daemon directly")
        print("   ./scripts/install_launchd.sh  # Run as background service on macOS")
        print("   ./scripts/install_systemd.sh  # Run as background service on Linux\n")


def main():
    parser = argparse.ArgumentParser(description="HorusOps Interactive CLI Configuration Wizard")
    parser.parse_args()

    try:
        run_interactive_wizard()
    except (KeyboardInterrupt, EOFError):
        print("\n\n[INFO] Configuration wizard aborted by user.")


if __name__ == "__main__":
    main()
