#!/usr/bin/env python3
"""WAISoft-Reports / git-auto-sync Web Configuration Wizard.

Zero external dependencies - runs on standard Python 3 library!
Opens a modern web interface on http://localhost:8585 to configure:
  - Telegram Bot credentials & Authorized user
  - Groq AI settings & model selection
  - GitHub integration token
  - Git projects base directory and ignore rules
  - Local server definitions (dynamic ports, start commands)
  - GitHub Actions CI/CD targets (Android APKs, Web builds)
"""

from __future__ import annotations

import http.server
import json
import os
import socket
import socketserver
import subprocess
import sys
import urllib.parse
import urllib.request
import webbrowser
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parent
ENV_FILE = ROOT_DIR / ".env"
SERVERS_FILE = ROOT_DIR / "servers.json"
TARGETS_FILE = ROOT_DIR / "targets.json"
CONFIG_FILE = ROOT_DIR / "config.toml"


def get_free_port(start_port: int = 8585) -> int:
    for port in range(start_port, start_port + 50):
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            if s.connect_ex(("127.0.0.1", port)) != 0:
                return port
    return start_port


def read_json_safe(path: Path, default_val: dict) -> dict:
    if path.is_file():
        try:
            with open(path, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception:
            pass
    return default_val


def parse_env_file(path: Path) -> dict[str, str]:
    data: dict[str, str] = {}
    if path.is_file():
        try:
            for line in path.read_text(encoding="utf-8").splitlines():
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, v = line.split("=", 1)
                    data[k.strip()] = v.strip().strip("'\"")
        except Exception:
            pass
    return data


def write_env_file(path: Path, env_data: dict[str, str]) -> None:
    lines = [
        "# ====================================================================",
        "# WAISoft-Reports / git-auto-sync Environment Configuration",
        "# Generated by Web Setup Wizard",
        "# ====================================================================",
        "",
        "# --- Telegram Bot Configuration ---",
        f'TELEGRAM_BOT_TOKEN="{env_data.get("TELEGRAM_BOT_TOKEN", "")}"',
        f'TELEGRAM_USER_ID="{env_data.get("TELEGRAM_USER_ID", "")}"',
        "",
        "# --- AI Provider (Groq Cloud) ---",
        f'GROQ_API_KEY="{env_data.get("GROQ_API_KEY", "")}"',
        f'GROQ_MODEL="{env_data.get("GROQ_MODEL", "qwen/qwen3.8-27b")}"',
        "",
        "# --- GitHub Integration Token ---",
        f'GITHUB_TOKEN="{env_data.get("GITHUB_TOKEN", "")}"',
        "",
        "# --- Multi-Repo Git Sync Settings ---",
        f'SYNC_BASE_DIR="{env_data.get("SYNC_BASE_DIR", "~/projects")}"',
        f'SYNC_IGNORED_NAMES="{env_data.get("SYNC_IGNORED_NAMES", "ignore,personal,archive")}"',
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")
    try:
        os.chmod(str(path), 0o600)
    except Exception:
        pass


def test_telegram_token(token: str) -> dict:
    if not token:
        return {"ok": False, "error": "يرجى إدخال توكن البوت أولاً."}
    url = f"https://api.telegram.org/bot{token}/getMe"
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "SetupWizard/1.0"})
        with urllib.request.urlopen(req, timeout=10) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            if data.get("ok"):
                user = data.get("result", {})
                return {
                    "ok": True,
                    "name": user.get("first_name", ""),
                    "username": user.get("username", ""),
                    "id": user.get("id"),
                }
            return {"ok": False, "error": data.get("description", "Unknown error")}
    except Exception as exc:
        return {"ok": False, "error": str(exc)}


def test_groq_key(key: str) -> dict:
    if not key:
        return {"ok": False, "error": "يرجى إدخال مفتاح Groq أولاً."}
    url = "https://api.groq.com/openai/v1/models"
    try:
        req = urllib.request.Request(
            url,
            headers={
                "Authorization": f"Bearer {key}",
                "User-Agent": "SetupWizard/1.0",
            },
        )
        with urllib.request.urlopen(req, timeout=10) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            models = [m.get("id") for m in data.get("data", []) if m.get("id")]
            return {"ok": True, "models_count": len(models), "models": models[:6]}
    except Exception as exc:
        return {"ok": False, "error": str(exc)}


def test_github_token(token: str) -> dict:
    if not token:
        return {"ok": False, "error": "يرجى إدخال توكن GitHub أولاً."}
    url = "https://api.github.com/user"
    try:
        req = urllib.request.Request(
            url,
            headers={
                "Authorization": f"token {token}",
                "User-Agent": "SetupWizard/1.0",
                "Accept": "application/vnd.github.v3+json",
            },
        )
        with urllib.request.urlopen(req, timeout=10) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            return {
                "ok": True,
                "login": data.get("login", ""),
                "name": data.get("name", ""),
            }
    except Exception as exc:
        return {"ok": False, "error": str(exc)}


class SetupRequestHandler(http.server.BaseHTTPRequestHandler):
    def log_message(self, format, *args):
        pass

    def _send_json(self, status_code: int, data: dict):
        body = json.dumps(data, ensure_ascii=False).encode("utf-8")
        self.send_response(status_code)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Access-Control-Allow-Origin", "*")
        self.end_headers()
        self.wfile.write(body)

    def do_OPTIONS(self):
        self.send_response(204)
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.end_headers()

    def do_GET(self):
        parsed = urllib.parse.urlparse(self.path)
        if parsed.path == "/":
            self.serve_html()
        elif parsed.path == "/api/config":
            env_data = parse_env_file(ENV_FILE)
            servers_data = read_json_safe(SERVERS_FILE, {})
            targets_data = read_json_safe(TARGETS_FILE, {})
            self._send_json(200, {
                "env": env_data,
                "servers": servers_data.get("servers", servers_data),
                "targets": targets_data.get("targets", targets_data),
            })
        else:
            self.send_error(404, "Not Found")

    def do_POST(self):
        parsed = urllib.parse.urlparse(self.path)
        length = int(self.headers.get("Content-Length", 0))
        raw_body = self.rfile.read(length).decode("utf-8") if length > 0 else "{}"
        try:
            body = json.loads(raw_body)
        except Exception:
            body = {}

        if parsed.path == "/api/test/telegram":
            res = test_telegram_token(body.get("token", "").strip())
            self._send_json(200, res)

        elif parsed.path == "/api/test/groq":
            res = test_groq_key(body.get("key", "").strip())
            self._send_json(200, res)

        elif parsed.path == "/api/test/github":
            res = test_github_token(body.get("token", "").strip())
            self._send_json(200, res)

        elif parsed.path == "/api/save":
            try:
                env_in = body.get("env", {})
                servers_in = body.get("servers", {})
                targets_in = body.get("targets", {})

                write_env_file(ENV_FILE, env_in)

                with open(SERVERS_FILE, "w", encoding="utf-8") as f:
                    json.dump({"servers": servers_in}, f, ensure_ascii=False, indent=2)

                with open(TARGETS_FILE, "w", encoding="utf-8") as f:
                    json.dump({"targets": targets_in}, f, ensure_ascii=False, indent=2)

                self._send_json(200, {"ok": True, "message": "تم حفظ كافة الإعدادات بنجاح في .env و servers.json و targets.json!"})
            except Exception as exc:
                self._send_json(500, {"ok": False, "error": str(exc)})

        elif parsed.path == "/api/start_bot":
            try:
                bot_script = ROOT_DIR / "telegram_bot_daemon.py"
                proc = subprocess.Popen(
                    [sys.executable, str(bot_script)],
                    cwd=str(ROOT_DIR),
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                    start_new_session=True,
                )
                self._send_json(200, {"ok": True, "pid": proc.pid, "message": f"تم إطلاق ديمون البوت بنجاح في الخلفية (PID: {proc.pid})"})
            except Exception as exc:
                self._send_json(500, {"ok": False, "error": str(exc)})
        else:
            self.send_error(404, "Not Found")

    def serve_html(self):
        html = HTML_PAGE.encode("utf-8")
        self.send_response(200)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Content-Length", str(len(html)))
        self.end_headers()
        self.wfile.write(html)


HTML_PAGE = """<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>WAISoft-Reports | معالج الإعداد التفاعلي</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@400;600;700;800&display=swap" rel="stylesheet">
  <style>
    body { font-family: "Cairo", sans-serif; }
    .tab-active { border-color: #3b82f6; color: #3b82f6; background-color: rgba(59, 130, 246, 0.08); }
  </style>
</head>
<body class="bg-slate-900 text-slate-100 min-h-screen">
  <div class="max-w-5xl mx-auto px-4 py-8">
    <!-- Header -->
    <header class="mb-8 flex flex-col md:flex-row items-center justify-between gap-4 border-b border-slate-800 pb-6">
      <div>
        <div class="flex items-center gap-3">
          <span class="px-2.5 py-1 bg-blue-600/20 text-blue-400 border border-blue-500/30 rounded font-mono text-xs font-bold">[SYS]</span>
          <h1 class="text-2xl md:text-3xl font-bold bg-gradient-to-r from-blue-400 to-indigo-300 bg-clip-text text-transparent">
            WAISoft-Reports | لوحة إعدادات النظام
          </h1>
        </div>
        <p class="text-sm text-slate-400 mt-1">
          واجهة تهيئة مفتوحة المصدر لإدارة المستودعات، المزامنة، الخوادم، وبوت تيليجرام.
        </p>
      </div>
      <div class="flex items-center gap-2">
        <button id="saveTopBtn" onclick="saveAllConfig()" class="px-5 py-2.5 bg-blue-600 hover:bg-blue-500 font-semibold rounded-lg shadow-lg shadow-blue-600/20 transition flex items-center gap-2 text-sm">
          [حفظ الإعدادات]
        </button>
        <button id="startBotTopBtn" onclick="startBotDaemon()" class="px-4 py-2.5 bg-emerald-600 hover:bg-emerald-500 font-semibold rounded-lg shadow-lg shadow-emerald-600/20 transition flex items-center gap-2 text-sm">
          [تشغيل البوت]
        </button>
      </div>
    </header>

    <!-- Notification Toast -->
    <div id="toast" class="hidden mb-6 p-4 rounded-xl text-sm font-medium transition duration-300 flex items-center justify-between shadow-lg">
      <span id="toastMsg"></span>
      <button onclick="hideToast()" class="text-slate-400 hover:text-white mr-4">x</button>
    </div>

    <!-- Navigation Tabs -->
    <div class="flex border-b border-slate-800 mb-6 gap-2 overflow-x-auto text-sm font-semibold">
      <button onclick="switchTab(1)" id="tabBtn1" class="px-4 py-3 rounded-t-lg border-b-2 border-transparent hover:text-blue-400 transition tab-active flex items-center gap-2">
        [1] مفاتيح الربط والخدمات
      </button>
      <button onclick="switchTab(2)" id="tabBtn2" class="px-4 py-3 rounded-t-lg border-b-2 border-transparent hover:text-blue-400 transition text-slate-400 flex items-center gap-2">
        [2] المستودعات والمزامنة
      </button>
      <button onclick="switchTab(3)" id="tabBtn3" class="px-4 py-3 rounded-t-lg border-b-2 border-transparent hover:text-blue-400 transition text-slate-400 flex items-center gap-2">
        [3] الخوادم والعمليات
      </button>
      <button onclick="switchTab(4)" id="tabBtn4" class="px-4 py-3 rounded-t-lg border-b-2 border-transparent hover:text-blue-400 transition text-slate-400 flex items-center gap-2">
        [4] خطوط البناء والـ CI/CD
      </button>
    </div>

    <!-- Tab 1: Tokens & AI -->
    <div id="tab1" class="space-y-6">
      <div class="bg-slate-800/60 border border-slate-700/60 rounded-2xl p-6 shadow-xl space-y-6">
        <h2 class="text-lg font-bold text-blue-400 flex items-center gap-2">
          إعدادات بوت تيليجرام
        </h2>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label class="block text-xs font-semibold text-slate-300 mb-2">توكن البوت (Bot Token)</label>
            <div class="flex gap-2">
              <input id="tgToken" type="password" placeholder="123456789:ABCdefGHI..." class="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:border-blue-500">
              <button onclick="testTelegram()" class="px-3 py-2 bg-slate-700 hover:bg-slate-600 text-xs font-semibold rounded-lg transition whitespace-nowrap">
                فحص الاتصال
              </button>
            </div>
            <p id="tgStatus" class="text-xs mt-1.5 text-slate-400"></p>
          </div>
          <div>
            <label class="block text-xs font-semibold text-slate-300 mb-2">معرف المستخدم المصرح له (Authorized User ID)</label>
            <input id="tgUserId" type="text" placeholder="123456789" class="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:border-blue-500">
            <p class="text-xs text-slate-500 mt-1">يضمن أن البوت يستجيب لأوامرك أنت فقط ويتجاهل أي مستخدم خارجي.</p>
          </div>
        </div>

        <div class="border-t border-slate-700/50 pt-6">
          <h2 class="text-lg font-bold text-purple-400 flex items-center gap-2 mb-4">
            محرك التحليل والتشخيص (Groq API)
          </h2>
          <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label class="block text-xs font-semibold text-slate-300 mb-2">مفتاح واجهة Groq (Groq API Key)</label>
              <div class="flex gap-2">
                <input id="groqKey" type="password" placeholder="gsk_..." class="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:border-purple-500">
                <button onclick="testGroq()" class="px-3 py-2 bg-slate-700 hover:bg-slate-600 text-xs font-semibold rounded-lg transition whitespace-nowrap">
                  فحص المفتاح
                </button>
              </div>
              <p id="groqStatus" class="text-xs mt-1.5 text-slate-400"></p>
            </div>
            <div>
              <label class="block text-xs font-semibold text-slate-300 mb-2">نموذج التحليل (Groq Model)</label>
              <select id="groqModel" class="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:border-purple-500 text-slate-200">
                <option value="qwen/qwen3.8-27b">Qwen 3.8 27B (الأفضل للتقارير والتشخيص الدقيق)</option>
                <option value="llama-3.3-70b-versatile">Llama 3.3 70B Versatile (عالي الدقة والسرعة)</option>
                <option value="llama-3.1-8b-instant">Llama 3.1 8B Instant (فائق السرعة)</option>
              </select>
            </div>
          </div>
        </div>

        <div class="border-t border-slate-700/50 pt-6">
          <h2 class="text-lg font-bold text-amber-400 flex items-center gap-2 mb-4">
            توكن GitHub الشخصي (Personal Access Token)
          </h2>
          <div class="max-w-lg">
            <label class="block text-xs font-semibold text-slate-300 mb-2">GitHub Token (لحزم الأندرويد و Actions)</label>
            <div class="flex gap-2">
              <input id="ghToken" type="password" placeholder="ghp_... أو gho_..." class="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:border-amber-500">
              <button onclick="testGithub()" class="px-3 py-2 bg-slate-700 hover:bg-slate-600 text-xs font-semibold rounded-lg transition whitespace-nowrap">
                فحص التوكن
              </button>
            </div>
            <p id="ghStatus" class="text-xs mt-1.5 text-slate-400"></p>
          </div>
        </div>
      </div>
    </div>

    <!-- Tab 2: Git & Repositories -->
    <div id="tab2" class="hidden space-y-6">
      <div class="bg-slate-800/60 border border-slate-700/60 rounded-2xl p-6 shadow-xl space-y-6">
        <h2 class="text-lg font-bold text-blue-400 flex items-center gap-2">
          مسار المشاريع وقواعد المزامنة
        </h2>
        <div class="space-y-4">
          <div>
            <label class="block text-xs font-semibold text-slate-300 mb-2">المسار الرئيسي لمجلد المشاريع (Projects Base Directory)</label>
            <input id="syncBaseDir" type="text" placeholder="~/projects أو /path/to/projects" class="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:border-blue-500">
            <p class="text-xs text-slate-500 mt-1">يقوم النظام باكتشاف كل مستودع Git داخل هذا المجلد تلقائياً ومزامنته بذكاء.</p>
          </div>
          <div>
            <label class="block text-xs font-semibold text-slate-300 mb-2">المجلدات المستثناة من الفحص (Ignored Folders)</label>
            <input id="syncIgnored" type="text" placeholder="ignore,personal,archive" class="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:border-blue-500">
            <p class="text-xs text-slate-500 mt-1">أسماء المجلدات المفصولة بفواصل التي يجب تجاهلها تماماً وعدم اعتبارها مشاريع عمل.</p>
          </div>
        </div>
      </div>
    </div>

    <!-- Tab 3: Local Servers -->
    <div id="tab3" class="hidden space-y-6">
      <div class="bg-slate-800/60 border border-slate-700/60 rounded-2xl p-6 shadow-xl space-y-6">
        <div class="flex items-center justify-between">
          <div>
            <h2 class="text-lg font-bold text-emerald-400 flex items-center gap-2">
              إدارة الخوادم المحلية للمشاريع
            </h2>
            <p class="text-xs text-slate-400 mt-1">
              عرّف خدمات مشاريعك ليتمكن البوت من تشغيلها، إيقافها، حل تعارض بورتاتها، وتشخيص أخطائها.
            </p>
          </div>
          <button onclick="addServerCard()" class="px-3.5 py-2 bg-emerald-600 hover:bg-emerald-500 text-xs font-bold rounded-lg transition flex items-center gap-1.5">
            [+] إضافة خدمة
          </button>
        </div>

        <div id="serversContainer" class="space-y-4">
          <!-- Server cards inserted dynamically -->
        </div>
      </div>
    </div>

    <!-- Tab 4: CI/CD Targets -->
    <div id="tab4" class="hidden space-y-6">
      <div class="bg-slate-800/60 border border-slate-700/60 rounded-2xl p-6 shadow-xl space-y-6">
        <div class="flex items-center justify-between">
          <div>
            <h2 class="text-lg font-bold text-amber-400 flex items-center gap-2">
              أهداف البناء ومراقبة GitHub Actions
            </h2>
            <p class="text-xs text-slate-400 mt-1">
              اربط الـ Workflows ليقوم البوت ببنائها وتحميل ملفات الـ APK مباشرة إليك في تيليجرام.
            </p>
          </div>
          <button onclick="addTargetCard()" class="px-3.5 py-2 bg-amber-600 hover:bg-amber-500 text-xs font-bold rounded-lg transition flex items-center gap-1.5">
            [+] إضافة هدف بناء
          </button>
        </div>

        <div id="targetsContainer" class="space-y-4">
          <!-- Target cards inserted dynamically -->
        </div>
      </div>
    </div>

    <!-- Footer -->
    <footer class="mt-12 text-center text-xs text-slate-500 border-t border-slate-800/80 pt-6">
      WAISoft-Reports &bull; مفتوح المصدر برخصة MIT &bull; يعمل محلياً بأمان تام بدون أي تسريب للبيانات.
    </footer>
  </div>

  <script>
    let currentConfig = { env: {}, servers: {}, targets: {} };

    function switchTab(index) {
      for (let i = 1; i <= 4; i++) {
        document.getElementById(`tab${i}`).classList.add("hidden");
        document.getElementById(`tabBtn${i}`).classList.remove("tab-active", "text-blue-400");
        document.getElementById(`tabBtn${i}`).classList.add("text-slate-400");
      }
      document.getElementById(`tab${index}`).classList.remove("hidden");
      document.getElementById(`tabBtn${index}`).classList.add("tab-active", "text-blue-400");
      document.getElementById(`tabBtn${index}`).classList.remove("text-slate-400");
    }

    function showToast(msg, isError = false) {
      const toast = document.getElementById("toast");
      const toastMsg = document.getElementById("toastMsg");
      toastMsg.innerText = msg;
      toast.className = isError
        ? "mb-6 p-4 rounded-xl text-sm font-medium transition duration-300 flex items-center justify-between shadow-lg bg-rose-950/80 border border-rose-800 text-rose-200"
        : "mb-6 p-4 rounded-xl text-sm font-medium transition duration-300 flex items-center justify-between shadow-lg bg-emerald-950/80 border border-emerald-800 text-emerald-200";
      toast.classList.remove("hidden");
      setTimeout(() => { toast.classList.add("hidden"); }, 5000);
    }

    function hideToast() {
      document.getElementById("toast").classList.add("hidden");
    }

    async function loadInitialConfig() {
      try {
        const res = await fetch("/api/config");
        if (res.ok) {
          currentConfig = await res.json();
          const env = currentConfig.env || {};
          document.getElementById("tgToken").value = env.TELEGRAM_BOT_TOKEN || "";
          document.getElementById("tgUserId").value = env.TELEGRAM_USER_ID || "";
          document.getElementById("groqKey").value = env.GROQ_API_KEY || "";
          document.getElementById("groqModel").value = env.GROQ_MODEL || "qwen/qwen3.8-27b";
          document.getElementById("ghToken").value = env.GITHUB_TOKEN || "";
          document.getElementById("syncBaseDir").value = env.SYNC_BASE_DIR || "~/projects";
          document.getElementById("syncIgnored").value = env.SYNC_IGNORED_NAMES || "ignore,personal,archive";

          renderServers(currentConfig.servers || {});
          renderTargets(currentConfig.targets || {});
        }
      } catch (err) {
        showToast("تعذر قراءة الإعدادات الحالية: " + err, true);
      }
    }

    function renderServers(servers) {
      const container = document.getElementById("serversContainer");
      container.innerHTML = "";
      const keys = Object.keys(servers);
      if (keys.length === 0) {
        container.innerHTML = `<p class="text-xs text-slate-500 py-4 text-center">لا توجد خدمات معرفة حالياً. اضغط على "إضافة خدمة" للبدء.</p>`;
        return;
      }
      keys.forEach((k) => {
        const s = servers[k];
        container.appendChild(createServerCard(k, s));
      });
    }

    function createServerCard(key, s) {
      const card = document.createElement("div");
      card.className = "bg-slate-900 border border-slate-800 rounded-xl p-4 space-y-3 relative server-entry";
      card.dataset.key = key;

      const cmdStr = Array.isArray(s.command) ? s.command.join(" ") : (s.command || "");

      card.innerHTML = `
        <div class="flex items-center justify-between border-b border-slate-800/80 pb-2">
          <input type="text" value="${key}" placeholder="service_key (e.g. web_app)" class="srv-key font-bold text-sm bg-transparent text-emerald-400 border-none focus:outline-none">
          <button onclick="this.closest('.server-entry').remove()" class="text-slate-500 hover:text-rose-400 text-xs font-semibold">x حذف</button>
        </div>
        <div class="grid grid-cols-1 md:grid-cols-3 gap-3 text-xs">
          <div>
            <label class="block text-slate-400 mb-1">اسم العرض (Title)</label>
            <input type="text" value="${s.title || ""}" class="srv-title w-full bg-slate-950 border border-slate-800 rounded px-2 py-1.5 focus:border-emerald-500">
          </div>
          <div>
            <label class="block text-slate-400 mb-1">اسم المشروع (Project)</label>
            <input type="text" value="${s.project || ""}" class="srv-project w-full bg-slate-950 border border-slate-800 rounded px-2 py-1.5 focus:border-emerald-500">
          </div>
          <div>
            <label class="block text-slate-400 mb-1">البورت الافتراضي (Port)</label>
            <input type="number" value="${s.default_port || 3000}" class="srv-port w-full bg-slate-950 border border-slate-800 rounded px-2 py-1.5 focus:border-emerald-500">
          </div>
          <div class="md:col-span-1">
            <label class="block text-slate-400 mb-1">مسار المجلد (CWD)</label>
            <input type="text" value="${s.cwd || "."}" class="srv-cwd w-full bg-slate-950 border border-slate-800 rounded px-2 py-1.5 focus:border-emerald-500">
          </div>
          <div class="md:col-span-2">
            <label class="block text-slate-400 mb-1">أمر التشغيل (Start Command مع {port})</label>
            <input type="text" value="${cmdStr}" placeholder="npm run dev -- --port {port}" class="srv-cmd w-full bg-slate-950 border border-slate-800 rounded px-2 py-1.5 focus:border-emerald-500 font-mono">
          </div>
        </div>
      `;
      return card;
    }

    function addServerCard() {
      const container = document.getElementById("serversContainer");
      const count = container.querySelectorAll(".server-entry").length + 1;
      const newKey = `service_${count}`;
      const dummy = {
        title: `خدمة جديدة (${count})`,
        project: "my-app",
        default_port: 3000 + count,
        cwd: ".",
        command: "npm run dev -- -p {port}",
      };
      container.appendChild(createServerCard(newKey, dummy));
    }

    function renderTargets(targets) {
      const container = document.getElementById("targetsContainer");
      container.innerHTML = "";
      const keys = Object.keys(targets);
      if (keys.length === 0) {
        container.innerHTML = `<p class="text-xs text-slate-500 py-4 text-center">لا توجد أهداف بناء مضافة حالياً.</p>`;
        return;
      }
      keys.forEach((k) => {
        container.appendChild(createTargetCard(k, targets[k]));
      });
    }

    function createTargetCard(key, t) {
      const card = document.createElement("div");
      card.className = "bg-slate-900 border border-slate-800 rounded-xl p-4 space-y-3 relative target-entry";
      card.dataset.key = key;

      card.innerHTML = `
        <div class="flex items-center justify-between border-b border-slate-800/80 pb-2">
          <input type="text" value="${key}" placeholder="target_key" class="tgt-key font-bold text-sm bg-transparent text-amber-400 border-none focus:outline-none">
          <button onclick="this.closest('.target-entry').remove()" class="text-slate-500 hover:text-rose-400 text-xs font-semibold">x حذف</button>
        </div>
        <div class="grid grid-cols-1 md:grid-cols-3 gap-3 text-xs">
          <div>
            <label class="block text-slate-400 mb-1">اسم العرض (Title)</label>
            <input type="text" value="${t.title || ""}" class="tgt-title w-full bg-slate-950 border border-slate-800 rounded px-2 py-1.5 focus:border-amber-500">
          </div>
          <div>
            <label class="block text-slate-400 mb-1">حساب GitHub (Owner)</label>
            <input type="text" value="${t.owner || ""}" class="tgt-owner w-full bg-slate-950 border border-slate-800 rounded px-2 py-1.5 focus:border-amber-500">
          </div>
          <div>
            <label class="block text-slate-400 mb-1">اسم المستودع (Repo)</label>
            <input type="text" value="${t.repo || ""}" class="tgt-repo w-full bg-slate-950 border border-slate-800 rounded px-2 py-1.5 focus:border-amber-500">
          </div>
          <div>
            <label class="block text-slate-400 mb-1">ملف الـ Workflow</label>
            <input type="text" value="${t.workflow || "build-android.yml"}" class="tgt-wf w-full bg-slate-950 border border-slate-800 rounded px-2 py-1.5 focus:border-amber-500">
          </div>
          <div>
            <label class="block text-slate-400 mb-1">الفرع (Branch)</label>
            <input type="text" value="${t.branch || "main"}" class="tgt-branch w-full bg-slate-950 border border-slate-800 rounded px-2 py-1.5 focus:border-amber-500">
          </div>
          <div>
            <label class="block text-slate-400 mb-1">نوع المخرج (Type)</label>
            <select class="tgt-type w-full bg-slate-950 border border-slate-800 rounded px-2 py-1.5 focus:border-amber-500">
              <option value="apk" ${t.type === "apk" ? "selected" : ""}>APK (Android Package)</option>
              <option value="deploy" ${t.type === "deploy" ? "selected" : ""}>Web Deploy</option>
            </select>
          </div>
        </div>
      `;
      return card;
    }

    function addTargetCard() {
      const container = document.getElementById("targetsContainer");
      const count = container.querySelectorAll(".target-entry").length + 1;
      const newKey = `target_${count}`;
      const dummy = {
        title: `تطبيق أندرويد (${count})`,
        owner: "your-org",
        repo: "my-app",
        workflow: "build-android.yml",
        branch: "main",
        type: "apk",
      };
      container.appendChild(createTargetCard(newKey, dummy));
    }

    async function testTelegram() {
      const token = document.getElementById("tgToken").value.trim();
      const status = document.getElementById("tgStatus");
      status.innerText = "جاري الفحص...";
      status.className = "text-xs mt-1.5 text-blue-400";
      const res = await fetch("/api/test/telegram", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ token }),
      });
      const data = await res.json();
      if (data.ok) {
        status.innerText = `[OK] متصل بنجاح: ${data.name} (@${data.username})`;
        status.className = "text-xs mt-1.5 text-emerald-400 font-semibold";
      } else {
        status.innerText = `[ERROR] فشل الاتصال: ${data.error}`;
        status.className = "text-xs mt-1.5 text-rose-400 font-semibold";
      }
    }

    async function testGroq() {
      const key = document.getElementById("groqKey").value.trim();
      const status = document.getElementById("groqStatus");
      status.innerText = "جاري الفحص...";
      status.className = "text-xs mt-1.5 text-blue-400";
      const res = await fetch("/api/test/groq", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ key }),
      });
      const data = await res.json();
      if (data.ok) {
        status.innerText = `[OK] المفتاح صالح (${data.models_count} نموذج متوفر)`;
        status.className = "text-xs mt-1.5 text-emerald-400 font-semibold";
      } else {
        status.innerText = `[ERROR] خطأ في المفتاح: ${data.error}`;
        status.className = "text-xs mt-1.5 text-rose-400 font-semibold";
      }
    }

    async function testGithub() {
      const token = document.getElementById("ghToken").value.trim();
      const status = document.getElementById("ghStatus");
      status.innerText = "جاري الفحص...";
      status.className = "text-xs mt-1.5 text-blue-400";
      const res = await fetch("/api/test/github", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ token }),
      });
      const data = await res.json();
      if (data.ok) {
        status.innerText = `[OK] التوكن صالح للمستخدم: @${data.login}`;
        status.className = "text-xs mt-1.5 text-emerald-400 font-semibold";
      } else {
        status.innerText = `[ERROR] خطأ في التوكن: ${data.error}`;
        status.className = "text-xs mt-1.5 text-rose-400 font-semibold";
      }
    }

    async function saveAllConfig() {
      const env = {
        TELEGRAM_BOT_TOKEN: document.getElementById("tgToken").value.trim(),
        TELEGRAM_USER_ID: document.getElementById("tgUserId").value.trim(),
        GROQ_API_KEY: document.getElementById("groqKey").value.trim(),
        GROQ_MODEL: document.getElementById("groqModel").value,
        GITHUB_TOKEN: document.getElementById("ghToken").value.trim(),
        SYNC_BASE_DIR: document.getElementById("syncBaseDir").value.trim(),
        SYNC_IGNORED_NAMES: document.getElementById("syncIgnored").value.trim(),
      };

      const servers = {};
      document.querySelectorAll(".server-entry").forEach((el) => {
        const k = el.querySelector(".srv-key").value.trim();
        if (k) {
          servers[k] = {
            title: el.querySelector(".srv-title").value.trim(),
            project: el.querySelector(".srv-project").value.trim(),
            default_port: parseInt(el.querySelector(".srv-port").value) || 3000,
            cwd: el.querySelector(".srv-cwd").value.trim() || ".",
            command: el.querySelector(".srv-cmd").value.trim(),
          };
        }
      });

      const targets = {};
      document.querySelectorAll(".target-entry").forEach((el) => {
        const k = el.querySelector(".tgt-key").value.trim();
        if (k) {
          targets[k] = {
            title: el.querySelector(".tgt-title").value.trim(),
            owner: el.querySelector(".tgt-owner").value.trim(),
            repo: el.querySelector(".tgt-repo").value.trim(),
            workflow: el.querySelector(".tgt-wf").value.trim(),
            branch: el.querySelector(".tgt-branch").value.trim(),
            type: el.querySelector(".tgt-type").value,
          };
        }
      });

      try {
        const res = await fetch("/api/save", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ env, servers, targets }),
        });
        const data = await res.json();
        if (data.ok) {
          showToast(data.message);
        } else {
          showToast("حدث خطأ أثناء الحفظ: " + data.error, true);
        }
      } catch (err) {
        showToast("تعذر الاتصال بالخادم: " + err, true);
      }
    }

    async function startBotDaemon() {
      try {
        const res = await fetch("/api/start_bot", { method: "POST" });
        const data = await res.json();
        if (data.ok) {
          showToast(data.message);
        } else {
          showToast("فشل إطلاق البوت: " + data.error, true);
        }
      } catch (err) {
        showToast("خطأ: " + err, true);
      }
    }

    window.addEventListener("DOMContentLoaded", loadInitialConfig);
  </script>
</body>
</html>
"""


def main():
    import argparse
    parser = argparse.ArgumentParser(description="WAISoft-Reports Web Setup Wizard")
    parser.add_argument("--port", type=int, default=8585, help="Port to run web wizard on (default: 8585)")
    args = parser.parse_args()

    port = get_free_port(args.port)
    socketserver.TCPServer.allow_reuse_address = True
    server_address = ("127.0.0.1", port)
    httpd = socketserver.TCPServer(server_address, SetupRequestHandler)
    url = f"http://localhost:{port}"

    print("=" * 65)
    print(" [SYSTEM] WAISoft-Reports | Web Configuration Console")
    print("=" * 65)
    print(f"\n[INFO] Configuration Console running at: {url}\n")
    print("Press Ctrl+C in this terminal to stop.")
    print("=" * 65)

    try:
        webbrowser.open(url)
    except Exception:
        pass

    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        print("\nShutting down setup wizard. Goodbye!")
        httpd.server_close()


if __name__ == "__main__":
    main()
