#!/usr/bin/env python3
"""
HorusOps | Setup & Configuration Wizard
A zero-dependency configuration generator for HorusOps:
- Validates Telegram Bot, Groq AI, and GitHub credentials.
- Auto-detects Telegram Chat ID from incoming messages.
- Scans and detects Git repositories across single or multiple base paths.
- Auto-discovers local project servers and port configurations.
- Writes .env, servers.json, and targets.json.
- Supports interactive terminal CLI mode (--cli) for headless servers.
"""

from __future__ import annotations

import http.server
import json
import os
import re
import socket
import socketserver
import ssl
import subprocess
import sys
import urllib.error
import urllib.parse
import urllib.request
import webbrowser
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parent
ENV_FILE = ROOT_DIR / ".env"
SERVERS_FILE = ROOT_DIR / "servers.json"
TARGETS_FILE = ROOT_DIR / "targets.json"
CONFIG_FILE = ROOT_DIR / "config.toml"
PROMPTS_DIR = ROOT_DIR / "prompts"

DEFAULT_PROMPTS = {
    "manager_report": (
        "أنت مستشار تنفيذي تقني. المطلوب كتابة تقرير إنجاز يومي موجه لمدير غير تقني يغطي دورة العمل: {shift_label}.\n"
        "شروط صارمة:\n"
        "1. ممنوع تماماً استخدام مصطلحات برمجية جافة (لا تذكر git, commit, branch, diff, hash, terminal).\n"
        "2. اكتب باختصار شديد وبشكل عملي: لخص ما تم إنجازه بنقاط واضحة (تحسينات الواجهة، إضافة ميزات، معالجة أخطاء، تجهيز بيئة العمل).\n"
        "3. التنسيق:\n"
        "[REPORT] تقرير إنجاز الأعمال اليومية\n"
        "• دورة العمل: {shift_label}\n"
        "• ملخص تنفيذي: سطر واحد موجز يوضح تقدم العمل.\n"
        "• المشاريع المنجزة: اسم المشروع وتحته نقطتان أو ثلاث توضح الأعمال المكتملة بلغة الأعمال.\n"
        "• الحالة: جاهز للمراجعة / قيد العمل."
    ),
    "diagnose": (
        "أنت محرك تشخيص أخطاء تقني (Diagnostic Engine) متخصص في هندسة النظم والـ DevOps.\n"
        "ردك تقني، مباشر، موجز، وخالٍ تماماً من أي إيموجيز أو مقدمات أو عبارات ترحيبية.\n"
        "حلل السجلات المرفقة، حدد السبب الجذري للخطأ (Root Cause)، واقترح الحل العملي المباشر في نقاط محددة."
    ),
    "chat": (
        "أنت محرك تحليل واستعلامات تشغيلي لنظام HorusOps.\n"
        "قواعد صارمة لأسلوب الرد:\n"
        "1. كن رسمياً، مهنياً، ومقتضباً إلى أقصى حد ممكن دون الإخلال بالمعلومة.\n"
        "2. ادخل في صلب الإجابة مباشرة بنقاط محددة، أرقام دقيقة، ومسارات صريحة.\n"
        "3. ممنوع تماماً أي عبارات ترحيبية، مجاملات، مقدمات، أو مشاعر.\n"
        "4. اعتمد فقط على بيانات المشاريع الحقيقية المرفقة في السياق بدقة تامة.\n"
        "5. راعِ سياق الرسائل السابقة المرفقة في التاريخ للإجابة دون طلب توضيح."
    ),
}


def read_prompts() -> dict[str, str]:
    prompts = {}
    for k, default_text in DEFAULT_PROMPTS.items():
        p_file = PROMPTS_DIR / f"{k}.txt"
        if p_file.is_file():
            try:
                prompts[k] = p_file.read_text(encoding="utf-8").strip()
                continue
            except Exception:
                pass
        prompts[k] = default_text
    return prompts


def write_prompts(prompts: dict[str, str]) -> None:
    PROMPTS_DIR.mkdir(parents=True, exist_ok=True)
    for k, text in prompts.items():
        if k in DEFAULT_PROMPTS and isinstance(text, str):
            p_file = PROMPTS_DIR / f"{k}.txt"
            p_file.write_text(text.strip(), encoding="utf-8")


def get_free_port(start_port: int = 8585) -> int:
    for port in range(start_port, start_port + 50):
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            if s.connect_ex(("127.0.0.1", port)) != 0:
                return port
    return start_port


def read_json_safe(path: Path, default_val: dict) -> dict:
    if path.is_file():
        try:
            with open(path, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception:
            pass
    return default_val


def parse_env_file(path: Path) -> dict[str, str]:
    data: dict[str, str] = {}
    if path.is_file():
        try:
            for line in path.read_text(encoding="utf-8").splitlines():
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, v = line.split("=", 1)
                    data[k.strip()] = v.strip().strip("'\"")
        except Exception:
            pass
    return data


def write_env_file(path: Path, env_data: dict[str, str]) -> None:
    lines = [
        "# ====================================================================",
        "# HorusOps / git-auto-sync Environment Configuration",
        "# Generated by Configuration Setup Wizard",
        "# ====================================================================",
        "",
        "# --- Telegram Bot Configuration ---",
        f'TELEGRAM_BOT_TOKEN="{env_data.get("TELEGRAM_BOT_TOKEN", "")}"',
        f'TELEGRAM_CHAT_ID="{env_data.get("TELEGRAM_CHAT_ID", "")}"',
        f'TELEGRAM_ADMIN_IDS="{env_data.get("TELEGRAM_ADMIN_IDS", env_data.get("TELEGRAM_CHAT_ID", ""))}"',
        "",
        "# --- AI & Diagnostic Engine (Groq) ---",
        f'GROQ_API_KEY="{env_data.get("GROQ_API_KEY", "")}"',
        f'GROQ_MODEL="{env_data.get("GROQ_MODEL", "llama-3.3-70b-versatile")}"',
        "",
        "# --- GitHub Integration ---",
        f'GITHUB_TOKEN="{env_data.get("GITHUB_TOKEN", "")}"',
        "",
        "# --- Git Auto Sync Settings ---",
        f'SYNC_BASE_DIR="{env_data.get("SYNC_BASE_DIR", "~/projects")}"',
        f'SYNC_IGNORED_NAMES="{env_data.get("SYNC_IGNORED_NAMES", "ignore,personal,archive,.git,node_modules,dist,build,.venv")}"',
        f'SYNC_PUSH="{env_data.get("SYNC_PUSH", "true")}"',
        f'SYNC_INTERVAL_MINUTES="{env_data.get("SYNC_INTERVAL_MINUTES", "30")}"',
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")
    try:
        os.chmod(str(path), 0o600)
    except Exception:
        pass


def safe_urlopen(req: urllib.request.Request, timeout: int = 10):
    try:
        return urllib.request.urlopen(req, timeout=timeout)
    except urllib.error.URLError as e:
        if "CERTIFICATE_VERIFY_FAILED" in str(e):
            ctx = ssl._create_unverified_context()
            return urllib.request.urlopen(req, timeout=timeout, context=ctx)
        raise


def test_telegram_token(token: str) -> dict:
    if not token:
        return {"ok": False, "error": "يرجى إدخال توكن البوت أولاً."}
    url = f"https://api.telegram.org/bot{token}/getMe"
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "SetupWizard/1.0"})
        with safe_urlopen(req, timeout=10) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            if data.get("ok"):
                user = data.get("result", {})
                return {
                    "ok": True,
                    "name": user.get("first_name", ""),
                    "username": user.get("username", ""),
                    "id": user.get("id"),
                }
            return {"ok": False, "error": data.get("description", "Unknown error")}
    except urllib.error.HTTPError as exc:
        try:
            d = json.loads(exc.read().decode("utf-8", errors="ignore"))
            return {"ok": False, "error": d.get("description", f"HTTP {exc.code}")}
        except Exception:
            return {"ok": False, "error": f"HTTP {exc.code}: {exc.reason}"}
    except Exception as exc:
        return {"ok": False, "error": str(exc)}


def detect_telegram_chat_id(token: str) -> dict:
    if not token:
        return {"ok": False, "error": "يرجى إدخال توكن البوت أولاً لتتمكن من فحص الرسائل."}
    url = f"https://api.telegram.org/bot{token}/getUpdates?limit=20&offset=-10"
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "SetupWizard/1.0"})
        with safe_urlopen(req, timeout=10) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            if not data.get("ok"):
                return {"ok": False, "error": data.get("description", "Unknown error")}
            updates = data.get("result", [])
            if not updates:
                return {
                    "ok": False,
                    "error": "لم يتم رصد أي رسائل واردة للبوت بعد. يرجى فتح البوت في تطبيق تيليجرام وإرسال أي رسالة له (مثل /start)، ثم الضغط على هذا الزر مجدداً.",
                }
            for item in reversed(updates):
                msg = item.get("message") or item.get("edited_message") or item.get("channel_post") or item.get("callback_query", {}).get("message")
                from_u = (item.get("message") or item.get("callback_query", {})).get("from", {})
                chat = msg.get("chat", {}) if msg else {}
                chat_id = from_u.get("id") or chat.get("id")
                if chat_id:
                    return {
                        "ok": True,
                        "chat_id": str(chat_id),
                        "name": from_u.get("first_name", "") or chat.get("title", ""),
                        "username": from_u.get("username", "") or chat.get("username", ""),
                    }
            return {
                "ok": False,
                "error": "تعذر استخراج معرّف مستخدم صالح من الرسائل الأخيرة. أرسل رسالة نصية جديدة للبوت ثم أعد المحاولة.",
            }
    except urllib.error.HTTPError as exc:
        try:
            d = json.loads(exc.read().decode("utf-8", errors="ignore"))
            return {"ok": False, "error": d.get("description", f"HTTP {exc.code}")}
        except Exception:
            return {"ok": False, "error": f"HTTP {exc.code}: {exc.reason}"}
    except Exception as exc:
        return {"ok": False, "error": str(exc)}


def test_groq_key(key: str) -> dict:
    if not key:
        return {"ok": False, "error": "يرجى إدخال مفتاح Groq أولاً."}
    url = "https://api.groq.com/openai/v1/models"
    try:
        req = urllib.request.Request(
            url,
            headers={
                "Authorization": f"Bearer {key}",
                "User-Agent": "SetupWizard/1.0",
            },
        )
        with safe_urlopen(req, timeout=10) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            models = [m.get("id") for m in data.get("data", []) if m.get("id")]
            return {"ok": True, "models_count": len(models), "models": models[:6]}
    except urllib.error.HTTPError as exc:
        try:
            d = json.loads(exc.read().decode("utf-8", errors="ignore"))
            msg = d.get("error", {}).get("message") or d.get("description")
            return {"ok": False, "error": msg or f"HTTP {exc.code}"}
        except Exception:
            return {"ok": False, "error": f"HTTP {exc.code}: {exc.reason}"}
    except Exception as exc:
        return {"ok": False, "error": str(exc)}


def test_github_token(token: str) -> dict:
    if not token:
        return {"ok": False, "error": "يرجى إدخال توكن GitHub أولاً."}
    url = "https://api.github.com/user"
    try:
        req = urllib.request.Request(
            url,
            headers={
                "Authorization": f"token {token}",
                "User-Agent": "SetupWizard/1.0",
                "Accept": "application/vnd.github.v3+json",
            },
        )
        with safe_urlopen(req, timeout=10) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            return {
                "ok": True,
                "login": data.get("login", ""),
                "name": data.get("name", ""),
            }
    except urllib.error.HTTPError as exc:
        try:
            d = json.loads(exc.read().decode("utf-8", errors="ignore"))
            return {"ok": False, "error": d.get("message", f"HTTP {exc.code}")}
        except Exception:
            return {"ok": False, "error": f"HTTP {exc.code}: {exc.reason}"}
    except Exception as exc:
        return {"ok": False, "error": str(exc)}


def select_folder_native() -> str:
    try:
        if sys.platform == "darwin":
            cmd = [
                "osascript",
                "-e",
                'try\nset f to POSIX path of (choose folder with prompt "اختر مجلد المشاريع:")\nreturn f\non error\nreturn ""\nend try',
            ]
            res = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
            return res.stdout.strip().rstrip("/")
        elif sys.platform.startswith("linux"):
            if subprocess.run(["which", "zenity"], capture_output=True).returncode == 0:
                res = subprocess.run(["zenity", "--file-selection", "--directory", "--title=اختر مجلد المشاريع"], capture_output=True, text=True, timeout=60)
                return res.stdout.strip().rstrip("/")
            elif subprocess.run(["which", "kdialog"], capture_output=True).returncode == 0:
                res = subprocess.run(["kdialog", "--getexistingdirectory"], capture_output=True, text=True, timeout=60)
                return res.stdout.strip().rstrip("/")
    except Exception:
        pass
    return ""


def get_repo_branch(repo_path: Path) -> str:
    head = repo_path / ".git" / "HEAD"
    if head.is_file():
        try:
            c = head.read_text().strip()
            if c.startswith("ref: refs/heads/"):
                return c.split("refs/heads/")[1]
        except Exception:
            pass
    return "main"


def scan_repositories_in_paths(paths: list[str]) -> list[dict]:
    repos = []
    seen = set()
    ignored = {"ignore", "personal", "archive", "node_modules", ".venv", "dist", "build", ".git"}
    for p_str in paths:
        if not p_str or not p_str.strip():
            continue
        p = Path(p_str.strip()).expanduser()
        if not p.is_dir():
            continue
        p_res = p.resolve()
        if (p_res / ".git").exists():
            r_str = str(p_res)
            if r_str not in seen:
                seen.add(r_str)
                repos.append({"name": p_res.name, "path": r_str, "branch": get_repo_branch(p_res)})
        try:
            for item in sorted(p_res.iterdir()):
                if item.is_dir() and item.name not in ignored and (item / ".git").exists():
                    r_str = str(item.resolve())
                    if r_str not in seen:
                        seen.add(r_str)
                        repos.append({"name": item.name, "path": r_str, "branch": get_repo_branch(item)})
        except Exception:
            pass
    return repos


def auto_scan_servers_in_paths(paths: list[str]) -> dict:
    repos = scan_repositories_in_paths(paths)
    servers = {}
    used_ports = set()

    for r in repos:
        r_path = Path(r["path"])
        name = r["name"]
        srv_key = re.sub(r"[^a-zA-Z0-9_]", "_", name.lower()).strip("_") or "srv"

        # 1. Node / JS
        pkg_file = r_path / "package.json"
        if pkg_file.is_file():
            try:
                pkg_data = json.loads(pkg_file.read_text(encoding="utf-8"))
                deps = {**pkg_data.get("dependencies", {}), **pkg_data.get("devDependencies", {})}
                scripts = pkg_data.get("scripts", {})
                port = 3000
                while port in used_ports:
                    port += 1
                used_ports.add(port)

                cmd = "npm run dev" if "dev" in scripts else ("npm start" if "start" in scripts else "node index.js")
                tech = "Node.js"
                if "next" in deps:
                    tech = "Next.js"
                elif "vite" in deps:
                    tech = "Vite"
                    port = 5173 if 5173 not in used_ports else port
                elif "react-scripts" in deps:
                    tech = "React"

                servers[srv_key] = {
                    "title": f"{name} ({tech})",
                    "project": name,
                    "cwd": str(r_path),
                    "command": cmd,
                    "default_port": port,
                }
                continue
            except Exception:
                pass

        # 2. Django
        if (r_path / "manage.py").is_file():
            port = 8000
            while port in used_ports:
                port += 1
            used_ports.add(port)
            servers[srv_key] = {
                "title": f"{name} (Django)",
                "project": name,
                "cwd": str(r_path),
                "command": f"python3 manage.py runserver {port}",
                "default_port": port,
            }
            continue

        # 3. FastAPI / Flask / Python
        if (r_path / "main.py").is_file() or (r_path / "app.py").is_file():
            port = 8000
            while port in used_ports:
                port += 1
            used_ports.add(port)
            main_text = ""
            try:
                if (r_path / "main.py").is_file():
                    main_text = (r_path / "main.py").read_text(encoding="utf-8", errors="ignore")
                elif (r_path / "app.py").is_file():
                    main_text = (r_path / "app.py").read_text(encoding="utf-8", errors="ignore")
            except Exception:
                pass

            if "FastAPI" in main_text or "fastapi" in main_text:
                cmd = "uvicorn main:app --reload"
                tech = "FastAPI"
            elif "Flask" in main_text or "flask" in main_text:
                cmd = "flask run"
                tech = "Flask"
                port = 5000 if 5000 not in used_ports else port
            else:
                cmd = "python3 main.py" if (r_path / "main.py").is_file() else "python3 app.py"
                tech = "Python"

            servers[srv_key] = {
                "title": f"{name} ({tech})",
                "project": name,
                "cwd": str(r_path),
                "command": cmd,
                "default_port": port,
            }

    return servers


class SetupRequestHandler(http.server.BaseHTTPRequestHandler):
    def log_message(self, format, *args):
        pass

    def _is_safe_host(self) -> bool:
        host = self.headers.get("Host", "").split(":")[0].strip().lower()
        return host in ("localhost", "127.0.0.1", "::1", "")

    def _send_json(self, status_code: int, data: dict):
        body = json.dumps(data, ensure_ascii=False).encode("utf-8")
        self.send_response(status_code)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("X-Frame-Options", "DENY")
        self.send_header("X-Content-Type-Options", "nosniff")
        self.end_headers()
        self.wfile.write(body)

    def do_OPTIONS(self):
        self.send_response(204)
        self.end_headers()

    def do_GET(self):
        if not self._is_safe_host():
            self.send_error(403, "Forbidden")
            return
        parsed = urllib.parse.urlparse(self.path)
        if parsed.path == "/":
            self.serve_html()
        elif parsed.path == "/api/config":
            env_data = parse_env_file(ENV_FILE)
            servers_data = read_json_safe(SERVERS_FILE, {})
            targets_data = read_json_safe(TARGETS_FILE, {})
            prompts_data = read_prompts()
            self._send_json(200, {
                "env": env_data,
                "servers": servers_data.get("servers", servers_data),
                "targets": targets_data.get("targets", targets_data),
                "prompts": prompts_data,
                "default_prompts": DEFAULT_PROMPTS,
            })
        elif parsed.path == "/api/select_folder":
            folder = select_folder_native()
            self._send_json(200, {"ok": True, "path": folder})
        else:
            self.send_error(404, "Not Found")

    def do_POST(self):
        if not self._is_safe_host():
            self.send_error(403, "Forbidden")
            return
        parsed = urllib.parse.urlparse(self.path)
        length = int(self.headers.get("Content-Length", 0))
        raw_body = self.rfile.read(length).decode("utf-8") if length > 0 else "{}"
        try:
            body = json.loads(raw_body)
        except Exception:
            body = {}

        if parsed.path in ("/api/test/telegram", "/api/validate/telegram"):
            token = body.get("token") or body.get("bot_token") or ""
            res = test_telegram_token(token.strip())
            self._send_json(200, res)

        elif parsed.path == "/api/detect/telegram_chat_id":
            token = body.get("token") or body.get("bot_token") or ""
            res = detect_telegram_chat_id(token.strip())
            self._send_json(200, res)

        elif parsed.path in ("/api/test/groq", "/api/validate/groq"):
            key = body.get("key") or body.get("api_key") or ""
            res = test_groq_key(key.strip())
            self._send_json(200, res)

        elif parsed.path in ("/api/test/github", "/api/validate/github"):
            token = body.get("token") or body.get("github_token") or ""
            res = test_github_token(token.strip())
            self._send_json(200, res)

        elif parsed.path == "/api/scan/repos":
            paths = body.get("paths") or body.get("base_dirs") or []
            if isinstance(paths, str):
                paths = [p.strip() for p in paths.split(",") if p.strip()]
            repos = scan_repositories_in_paths(paths)
            self._send_json(200, {"ok": True, "repos": repos, "count": len(repos)})

        elif parsed.path == "/api/scan/servers":
            paths = body.get("paths") or body.get("base_dirs") or []
            if isinstance(paths, str):
                paths = [p.strip() for p in paths.split(",") if p.strip()]
            servers = auto_scan_servers_in_paths(paths)
            self._send_json(200, {"ok": True, "servers": servers, "count": len(servers)})

        elif parsed.path == "/api/save":
            try:
                env_in = body.get("env", {})
                servers_in = body.get("servers", {})
                targets_in = body.get("targets", {})
                prompts_in = body.get("prompts", {})

                write_env_file(ENV_FILE, env_in)

                with open(SERVERS_FILE, "w", encoding="utf-8") as f:
                    json.dump({"servers": servers_in}, f, ensure_ascii=False, indent=2)

                with open(TARGETS_FILE, "w", encoding="utf-8") as f:
                    json.dump({"targets": targets_in}, f, ensure_ascii=False, indent=2)

                if prompts_in and isinstance(prompts_in, dict):
                    write_prompts(prompts_in)

                self._send_json(200, {
                    "ok": True,
                    "message": "تم حفظ الإعدادات بنجاح في .env و servers.json و targets.json ومجلد prompts. يمكنك الآن تشغيل البوت عبر: ./scripts/run_bot.sh"
                })
            except Exception as exc:
                self._send_json(500, {"ok": False, "error": str(exc)})
        else:
            self.send_error(404, "Not Found")

    def serve_html(self):
        html = HTML_PAGE.encode("utf-8")
        self.send_response(200)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Content-Length", str(len(html)))
        self.end_headers()
        self.wfile.write(html)


HTML_PAGE = """<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>HorusOps | معالج تهيئة إعدادات البوت والخدمات</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@400;600;700;800&family=JetBrains+Mono:wght@400;600&display=swap" rel="stylesheet">
  <style>
    body { font-family: "Cairo", sans-serif; }
    code, pre, .font-mono { font-family: "JetBrains Mono", monospace; }
    .tab-active { border-color: #3b82f6; color: #3b82f6; background-color: rgba(59, 130, 246, 0.08); }
  </style>
</head>
<body class="bg-slate-900 text-slate-100 min-h-screen">
  <div class="max-w-5xl mx-auto px-4 py-8">
    <!-- Header -->
    <header class="mb-8 flex flex-col md:flex-row items-center justify-between gap-4 border-b border-slate-800 pb-6">
      <div>
        <div class="flex items-center gap-3">
          <span class="px-2.5 py-1 bg-blue-600/20 text-blue-400 border border-blue-500/30 rounded font-mono text-xs font-bold">[HORUS-OPS]</span>
          <h1 class="text-2xl md:text-3xl font-bold bg-gradient-to-r from-blue-400 to-indigo-300 bg-clip-text text-transparent">
            HorusOps | معالج تهيئة إعدادات البوت
          </h1>
        </div>
        <p class="text-sm text-slate-400 mt-1">
          أداة لتهيئة وتوليد ملفات الضبط (.env و servers.json و targets.json). يتم تشغيل البوت وإدارته بالكامل من سطر الأوامر وتيليجرام.
        </p>
      </div>
      <div>
        <button id="saveTopBtn" onclick="saveAllConfig()" class="px-6 py-2.5 bg-blue-600 hover:bg-blue-500 font-semibold rounded-lg shadow-lg shadow-blue-600/20 transition flex items-center gap-2 text-sm">
          [حفظ ملفات الإعدادات]
        </button>
      </div>
    </header>

    <!-- Notification Toast -->
    <div id="toast" class="hidden mb-6 p-4 rounded-xl text-sm font-medium transition duration-300 flex items-center justify-between shadow-lg">
      <span id="toastMsg"></span>
      <button onclick="hideToast()" class="text-slate-400 hover:text-white mr-4">x</button>
    </div>

    <!-- Navigation Tabs -->
    <div class="flex border-b border-slate-800 mb-6 gap-2 overflow-x-auto text-sm font-semibold">
      <button onclick="switchTab(1)" id="tabBtn1" class="px-4 py-3 rounded-t-lg border-b-2 border-transparent hover:text-blue-400 transition tab-active flex items-center gap-2">
        [1] الإعدادات الأساسية للبدء
      </button>
      <button onclick="switchTab(2)" id="tabBtn2" class="px-4 py-3 rounded-t-lg border-b-2 border-transparent hover:text-blue-400 transition text-slate-400 flex items-center gap-2">
        [2] قواعد المزامنة وجدولة Git
      </button>
      <button onclick="switchTab(3)" id="tabBtn3" class="px-4 py-3 rounded-t-lg border-b-2 border-transparent hover:text-blue-400 transition text-slate-400 flex items-center gap-2">
        [3] خوادم ومنافذ المشاريع
      </button>
      <button onclick="switchTab(4)" id="tabBtn4" class="px-4 py-3 rounded-t-lg border-b-2 border-transparent hover:text-blue-400 transition text-slate-400 flex items-center gap-2">
        [4] خطوط البناء والـ CI/CD
      </button>
      <button onclick="switchTab(5)" id="tabBtn5" class="px-4 py-3 rounded-t-lg border-b-2 border-transparent hover:text-blue-400 transition text-slate-400 flex items-center gap-2">
        [5] موجهات الذكاء الاصطناعي (AI Prompts)
      </button>
    </div>

    <!-- Tab 1: Core Essentials -->
    <div id="tab1" class="space-y-6">
      <div class="bg-slate-800/60 border border-slate-700/60 rounded-2xl p-6 shadow-xl space-y-6">
        <div class="border-b border-slate-700/50 pb-4">
          <h2 class="text-lg font-bold text-blue-400 flex items-center gap-2">
            الحقول الأساسية المطلوبة للتشغيل (3 خطوات بسيطة)
          </h2>
          <p class="text-xs text-slate-400 mt-1">هذه الحقول كافية تماماً لتوليد ملفات الإعدادات وبدء تشغيل البوت فوراً.</p>
        </div>

        <!-- 1. Telegram Bot Token -->
        <div class="space-y-2">
          <div class="flex items-center justify-between">
            <label class="block text-xs font-semibold text-slate-200">1. توكن بوت تيليجرام (Telegram Bot Token) <span class="text-rose-400">*</span></label>
            <a href="https://t.me/BotFather" target="_blank" class="text-xs text-blue-400 hover:underline inline-flex items-center gap-1 font-mono">
              [إنشاء بوت عبر @BotFather]
            </a>
          </div>
          <div class="flex gap-2">
            <input id="tgToken" type="password" placeholder="123456789:ABCdefGHI..." class="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:border-blue-500 font-mono">
            <button onclick="testTelegram()" class="px-4 py-2 bg-slate-700 hover:bg-slate-600 text-xs font-semibold rounded-lg transition whitespace-nowrap">
              فحص الاتصال
            </button>
          </div>
          <p id="tgStatus" class="text-xs mt-1 text-slate-400"></p>
        </div>

        <!-- 2. Telegram User ID with Auto-Detect -->
        <div class="space-y-2 pt-2">
          <div class="flex items-center justify-between">
            <label class="block text-xs font-semibold text-slate-200">2. معرّف المستخدم المصرح له (Authorized User ID) <span class="text-rose-400">*</span></label>
            <span class="text-xs text-slate-500">يضمن استجابة البوت لك وحدك</span>
          </div>
          <div class="flex gap-2">
            <input id="tgUserId" type="text" placeholder="مثال: 590209605" class="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:border-blue-500 font-mono">
            <button onclick="detectChatId()" class="px-4 py-2 bg-indigo-600 hover:bg-indigo-500 text-xs font-bold rounded-lg transition whitespace-nowrap text-white">
              التقاط المعرّف تلقائياً
            </button>
          </div>
          <p id="detectStatus" class="text-xs mt-1 text-slate-400">
            أرسل كلمة Start أو أي رسالة لبوك في تيليجرام، ثم اضغط زر "التقاط المعرّف تلقائياً" ليتم جلبه فوراً.
          </p>
        </div>

        <!-- 3. Projects Directories with Multi-Folder and Browse -->
        <div class="space-y-2 pt-2 border-t border-slate-700/40 pt-4">
          <div class="flex items-center justify-between">
            <label class="block text-xs font-semibold text-slate-200">3. مسارات مجلدات المشاريع (Projects Directories) <span class="text-rose-400">*</span></label>
            <span class="text-xs text-slate-400">يمكنك إضافة أكثر من مجلد</span>
          </div>
          <div class="flex gap-2">
            <input id="syncBaseDir" type="text" placeholder="/path/to/projects, /another/path/projects" class="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:border-blue-500 font-mono">
            <button onclick="browseFolder()" class="px-4 py-2 bg-slate-700 hover:bg-slate-600 text-xs font-semibold rounded-lg transition whitespace-nowrap">
              تصفح مجلد...
            </button>
          </div>
          <div class="flex items-center justify-between pt-1">
            <p id="repoScanStatus" class="text-xs text-slate-400 font-mono">جاري فحص المسارات...</p>
            <button onclick="scanCurrentRepos()" class="text-xs text-blue-400 hover:underline">
              [إعادة فحص المستودعات]
            </button>
          </div>
          <div id="foundReposList" class="hidden mt-2 p-3 bg-slate-950/60 rounded-lg border border-slate-800 text-xs space-y-1 font-mono text-slate-300 max-h-36 overflow-y-auto"></div>
        </div>

        <!-- Optional 4: Groq API Key -->
        <div class="space-y-2 border-t border-slate-700/40 pt-4">
          <div class="flex items-center justify-between">
            <label class="block text-xs font-semibold text-slate-200">4. مفتاح Groq API للتحليل وتشخيص الأخطاء (اختياري)</label>
            <a href="https://console.groq.com/keys" target="_blank" class="text-xs text-purple-400 hover:underline inline-flex items-center gap-1 font-mono">
              [الحصول على مفتاح Groq مجاناً]
            </a>
          </div>
          <div class="grid grid-cols-1 md:grid-cols-2 gap-3">
            <div>
              <div class="flex gap-2">
                <input id="groqKey" type="password" placeholder="gsk_..." class="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:border-purple-500 font-mono">
                <button onclick="testGroq()" class="px-3 py-2 bg-slate-700 hover:bg-slate-600 text-xs font-semibold rounded-lg transition whitespace-nowrap">
                  فحص
                </button>
              </div>
              <p id="groqStatus" class="text-xs mt-1 text-slate-400"></p>
            </div>
            <div>
              <select id="groqModel" class="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:border-purple-500 text-slate-200">
                <option value="llama-3.3-70b-versatile">Llama 3.3 70B Versatile (النموذج الموصى به)</option>
                <option value="qwen/qwen3.8-27b">Qwen 3.8 27B</option>
                <option value="llama-3.1-8b-instant">Llama 3.1 8B Instant (فائق السرعة)</option>
              </select>
            </div>
          </div>
        </div>

        <!-- Optional 5: GitHub Token -->
        <div class="space-y-2 border-t border-slate-700/40 pt-4">
          <div class="flex items-center justify-between">
            <label class="block text-xs font-semibold text-slate-200">5. توكن GitHub لحزم وتطبيقات Actions (اختياري)</label>
            <a href="https://github.com/settings/tokens/new?scopes=repo,workflow" target="_blank" class="text-xs text-amber-400 hover:underline inline-flex items-center gap-1 font-mono">
              [توليد توكن GitHub]
            </a>
          </div>
          <div class="flex gap-2 max-w-xl">
            <input id="ghToken" type="password" placeholder="ghp_..." class="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:border-amber-500 font-mono">
            <button onclick="testGithub()" class="px-4 py-2 bg-slate-700 hover:bg-slate-600 text-xs font-semibold rounded-lg transition whitespace-nowrap">
              فحص التوكن
            </button>
          </div>
          <p id="ghStatus" class="text-xs mt-1 text-slate-400"></p>
        </div>
      </div>
    </div>

    <!-- Tab 2: Git Rules & Schedule -->
    <div id="tab2" class="hidden space-y-6">
      <div class="bg-slate-800/60 border border-slate-700/60 rounded-2xl p-6 shadow-xl space-y-4">
        <h2 class="text-lg font-bold text-blue-400">قواعد المزامنة وجدولة Git</h2>
        <div>
          <label class="block text-xs font-semibold text-slate-300 mb-2">المجلدات المستثناة من الفحص (Ignored Folders)</label>
          <input id="syncIgnored" type="text" value="ignore,personal,archive,.git,node_modules,dist,build,.venv" class="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:border-blue-500 font-mono">
          <p class="text-xs text-slate-500 mt-1">أسماء المجلدات المفصولة بفواصل التي يجب تجاهلها تماماً وعدم اعتبارها مشاريع عمل.</p>
        </div>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4 pt-2">
          <div>
            <label class="block text-xs font-semibold text-slate-300 mb-2">فترة المزامنة الدورية (بالدقائق)</label>
            <input id="syncInterval" type="number" value="30" class="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:border-blue-500 font-mono">
          </div>
          <div>
            <label class="block text-xs font-semibold text-slate-300 mb-2">الرفع التلقائي إلى GitHub (Auto Push)</label>
            <select id="syncPush" class="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:border-blue-500 text-slate-200">
              <option value="true">تفعيل الرفع التلقائي (true)</option>
              <option value="false">اكتفاء بالحفظ المحلي فقط (false)</option>
            </select>
          </div>
        </div>
      </div>
    </div>

    <!-- Tab 3: Local Servers Definitions -->
    <div id="tab3" class="hidden space-y-6">
      <div class="bg-slate-800/60 border border-slate-700/60 rounded-2xl p-6 shadow-xl space-y-6">
        <div class="flex flex-col md:flex-row md:items-center justify-between gap-3">
          <div>
            <h2 class="text-lg font-bold text-emerald-400">
              تعريف الخوادم ومنافذ المشاريع (servers.json)
            </h2>
            <p class="text-xs text-slate-400 mt-1">
              تعريف الخوادم ومنافذها ليتعرف عليها البوت لمراقبتها في التقارير. هذه الصفحة للتهيئة فقط ولا تقوم بتشغيل أي خدمات.
            </p>
          </div>
          <div class="flex items-center gap-2">
            <button onclick="autoDiscoverServers()" class="px-3.5 py-2 bg-indigo-600 hover:bg-indigo-500 text-xs font-bold rounded-lg transition text-white whitespace-nowrap">
              اكتشاف الخوادم تلقائياً من المشاريع
            </button>
            <button onclick="addServerCard()" class="px-3.5 py-2 bg-emerald-600 hover:bg-emerald-500 text-xs font-bold rounded-lg transition whitespace-nowrap">
              [+] إضافة خدمة
            </button>
          </div>
        </div>

        <div id="serversContainer" class="space-y-4">
          <!-- Server cards inserted dynamically -->
        </div>
      </div>
    </div>

    <!-- Tab 4: CI/CD Targets Definitions -->
    <div id="tab4" class="hidden space-y-6">
      <div class="bg-slate-800/60 border border-slate-700/60 rounded-2xl p-6 shadow-xl space-y-6">
        <div class="flex items-center justify-between">
          <div>
            <h2 class="text-lg font-bold text-amber-400">
              تعريف أهداف البناء (targets.json)
            </h2>
            <p class="text-xs text-slate-400 mt-1">
              تعريف مستهدفات البناء وخطوط سير العمل ليتعرف عليها البوت عند طلب البناء عبر أوامر تيليجرام.
            </p>
          </div>
          <button onclick="addTargetCard()" class="px-3.5 py-2 bg-amber-600 hover:bg-amber-500 text-xs font-bold rounded-lg transition flex items-center gap-1.5">
            [+] إضافة هدف بناء
          </button>
        </div>

        <div id="targetsContainer" class="space-y-4">
          <!-- Target cards inserted dynamically -->
        </div>
      </div>
    </div>

    <!-- Tab 5: AI System Prompts -->
    <div id="tab5" class="space-y-6 hidden">
      <div class="bg-slate-800/60 border border-slate-700/60 rounded-2xl p-6 shadow-xl space-y-6">
        <div class="border-b border-slate-700/50 pb-4">
          <h2 class="text-lg font-bold text-blue-400 flex items-center gap-2">
            تخصيص موجهات النظام للذكاء الاصطناعي (AI System Prompts)
          </h2>
          <p class="text-xs text-slate-400 mt-1">
            يمكنك تخصيص الأسلوب، لغة التقرير، وشروط التحليل لكل وظيفة من وظائف الذكاء الاصطناعي. تُحفظ هذه الموجهات في مجلد <code class="text-amber-400 font-mono">prompts/</code> في جذر المشروع.
          </p>
        </div>

        <!-- Prompt 1: Manager Report -->
        <div class="bg-slate-900/60 border border-slate-700/60 rounded-xl p-5 space-y-3">
          <div class="flex items-center justify-between">
            <div>
              <h3 class="text-sm font-bold text-slate-200">1. موجه التقرير الإداري التنفيذي (/managerreport)</h3>
              <p class="text-xs text-slate-400">يستخدم عند طلب تقرير ملخص لإنجاز اليوم موجه للإدارة. المتغير <code class="text-blue-400 font-mono">{shift_label}</code> يتم استبداله تلقائياً بتوقيت واسم الوردية.</p>
            </div>
            <button type="button" onclick="resetPrompt('manager_report')" class="text-xs text-slate-400 hover:text-blue-400 underline font-mono">
              [استعادة الافتراضي]
            </button>
          </div>
          <textarea id="promptManagerReport" rows="8" class="w-full bg-slate-950 border border-slate-700 rounded-lg p-3 text-xs text-slate-200 font-mono focus:border-blue-500 focus:outline-none leading-relaxed"></textarea>
        </div>

        <!-- Prompt 2: Diagnostics -->
        <div class="bg-slate-900/60 border border-slate-700/60 rounded-xl p-5 space-y-3">
          <div class="flex items-center justify-between">
            <div>
              <h3 class="text-sm font-bold text-slate-200">2. موجه تشخيص الأعطال وتحليل السجلات (/diagnose)</h3>
              <p class="text-xs text-slate-400">يستخدم عند توقف أي خادم أو عند فحص أخطاء التشغيل وسجلات Logs لاقتراح الحل الجذري.</p>
            </div>
            <button type="button" onclick="resetPrompt('diagnose')" class="text-xs text-slate-400 hover:text-blue-400 underline font-mono">
              [استعادة الافتراضي]
            </button>
          </div>
          <textarea id="promptDiagnose" rows="6" class="w-full bg-slate-950 border border-slate-700 rounded-lg p-3 text-xs text-slate-200 font-mono focus:border-blue-500 focus:outline-none leading-relaxed"></textarea>
        </div>

        <!-- Prompt 3: Smart Chat & Ops -->
        <div class="bg-slate-900/60 border border-slate-700/60 rounded-xl p-5 space-y-3">
          <div class="flex items-center justify-between">
            <div>
              <h3 class="text-sm font-bold text-slate-200">3. موجه الاستعلامات الذكية والمحادثة الصوتية/النصية</h3>
              <p class="text-xs text-slate-400">يحدد نبرة وقواعد الرد عندما يرسل المستخدم أسئلة أو رسائل صوتية حول حالة المشاريع والنظام.</p>
            </div>
            <button type="button" onclick="resetPrompt('chat')" class="text-xs text-slate-400 hover:text-blue-400 underline font-mono">
              [استعادة الافتراضي]
            </button>
          </div>
          <textarea id="promptChat" rows="6" class="w-full bg-slate-950 border border-slate-700 rounded-lg p-3 text-xs text-slate-200 font-mono focus:border-blue-500 focus:outline-none leading-relaxed"></textarea>
        </div>
      </div>
    </div>

    <!-- Instructions Box -->
    <div class="mt-8 bg-slate-800/40 border border-slate-700/40 rounded-xl p-5 text-xs text-slate-400 space-y-2">
      <div class="font-bold text-slate-300 text-sm">[INFO] طريقة تشغيل وإدارة البوت بعد حفظ الإعدادات:</div>
      <p>هذا المعالج مخصص فقط لتوليد وضبط ملفات الإعدادات (<code class="text-blue-400 font-mono">.env</code> و <code class="text-emerald-400 font-mono">servers.json</code> و <code class="text-amber-400 font-mono">targets.json</code>).</p>
      <p>بعد الضغط على [حفظ ملفات الإعدادات]، يتم تشغيل البوت وإدارته من خلال سطر الأوامر أو كخدمة خلفية:</p>
      <div class="bg-slate-950/80 p-3 rounded font-mono text-slate-300 text-xs space-y-1">
        <div># تشغيل البوت مباشرة:</div>
        <div class="text-emerald-400">./scripts/run_bot.sh</div>
        <div class="pt-2"># أو تثبيته كخدمة تعمل تلقائياً في خلفية النظام:</div>
        <div class="text-blue-400">./scripts/install_launchd.sh   # macOS</div>
        <div class="text-blue-400">./scripts/install_systemd.sh   # Linux</div>
      </div>
    </div>

    <!-- Footer -->
    <footer class="mt-12 text-center text-xs text-slate-500 border-t border-slate-800/80 pt-6">
      HorusOps &bull; مفتوح المصدر برخصة MIT &bull; يعمل محلياً بأمان تام بدون أي تسريب للبيانات.
    </footer>
  </div>

  <script>
    function showToast(msg, isError = false) {
      const t = document.getElementById("toast");
      const m = document.getElementById("toastMsg");
      m.innerText = msg;
      t.className = isError
        ? "mb-6 p-4 rounded-xl text-sm font-medium transition duration-300 flex items-center justify-between shadow-lg bg-rose-950/80 border border-rose-800 text-rose-200 block"
        : "mb-6 p-4 rounded-xl text-sm font-medium transition duration-300 flex items-center justify-between shadow-lg bg-emerald-950/80 border border-emerald-800 text-emerald-200 block";
      window.scrollTo({ top: 0, behavior: "smooth" });
    }

    function hideToast() {
      document.getElementById("toast").className = "hidden";
    }

    function switchTab(index) {
      for (let i = 1; i <= 5; i++) {
        const t = document.getElementById(`tab${i}`);
        const b = document.getElementById(`tabBtn${i}`);
        if (t) t.classList.add("hidden");
        if (b) {
          b.classList.remove("tab-active", "text-blue-400");
          b.classList.add("text-slate-400");
        }
      }
      const activeTab = document.getElementById(`tab${index}`);
      const activeBtn = document.getElementById(`tabBtn${index}`);
      if (activeTab) activeTab.classList.remove("hidden");
      if (activeBtn) {
        activeBtn.classList.add("tab-active", "text-blue-400");
        activeBtn.classList.remove("text-slate-400");
      }
    }

    function resetPrompt(key) {
      if (configState.default_prompts && configState.default_prompts[key]) {
        if (key === "manager_report") document.getElementById("promptManagerReport").value = configState.default_prompts[key];
        if (key === "diagnose") document.getElementById("promptDiagnose").value = configState.default_prompts[key];
        if (key === "chat") document.getElementById("promptChat").value = configState.default_prompts[key];
        showToast("تمت استعادة نص الموجه الافتراضي.");
      }
    }

    let configState = { env: {}, servers: {}, targets: {}, prompts: {}, default_prompts: {} };

    async function loadInitialConfig() {
      try {
        const res = await fetch("/api/config");
        const data = await res.json();
        configState = data;
        const env = data.env || {};

        if (env.TELEGRAM_BOT_TOKEN) document.getElementById("tgToken").value = env.TELEGRAM_BOT_TOKEN;
        if (env.TELEGRAM_ADMIN_IDS || env.TELEGRAM_CHAT_ID) {
          document.getElementById("tgUserId").value = env.TELEGRAM_ADMIN_IDS || env.TELEGRAM_CHAT_ID;
        }
        if (env.GROQ_API_KEY) document.getElementById("groqKey").value = env.GROQ_API_KEY;
        if (env.GROQ_MODEL) document.getElementById("groqModel").value = env.GROQ_MODEL;
        if (env.GITHUB_TOKEN) document.getElementById("ghToken").value = env.GITHUB_TOKEN;
        if (env.SYNC_BASE_DIR) document.getElementById("syncBaseDir").value = env.SYNC_BASE_DIR;
        if (env.SYNC_IGNORED_NAMES) document.getElementById("syncIgnored").value = env.SYNC_IGNORED_NAMES;
        if (env.SYNC_INTERVAL_MINUTES) document.getElementById("syncInterval").value = env.SYNC_INTERVAL_MINUTES;
        if (env.SYNC_PUSH) document.getElementById("syncPush").value = env.SYNC_PUSH;

        const prompts = data.prompts || {};
        if (prompts.manager_report) document.getElementById("promptManagerReport").value = prompts.manager_report;
        if (prompts.diagnose) document.getElementById("promptDiagnose").value = prompts.diagnose;
        if (prompts.chat) document.getElementById("promptChat").value = prompts.chat;

        renderServers(data.servers || {});
        renderTargets(data.targets || {});
        scanCurrentRepos();
      } catch (err) {
        showToast("تعذر قراءة الإعدادات الحالية: " + err, true);
      }
    }

    function renderServers(servers) {
      const container = document.getElementById("serversContainer");
      container.innerHTML = "";
      const keys = Object.keys(servers);
      if (keys.length === 0) {
        container.innerHTML = `<p class="text-xs text-slate-500 py-4 text-center">لا توجد خوادم معرفة حالياً. يمكنك الضغط على "اكتشاف الخوادم تلقائياً" لجلبها من مشاريعك فوراً.</p>`;
        return;
      }
      keys.forEach((k) => addServerCard(k, servers[k]));
    }

    function addServerCard(key = "", data = {}) {
      const container = document.getElementById("serversContainer");
      if (container.querySelector("p")) container.innerHTML = "";
      const card = document.createElement("div");
      card.className = "server-entry bg-slate-900/90 border border-slate-700/80 rounded-xl p-4 space-y-3";
      card.innerHTML = `
        <div class="flex items-center justify-between border-b border-slate-800/80 pb-2">
          <input type="text" value="${key}" placeholder="service_key (e.g. web_app)" class="srv-key font-bold text-sm bg-transparent text-emerald-400 border-none focus:outline-none font-mono">
          <button onclick="this.closest('.server-entry').remove()" class="text-slate-500 hover:text-rose-400 text-xs font-semibold">x حذف</button>
        </div>
        <div class="grid grid-cols-1 md:grid-cols-3 gap-3 text-xs">
          <div>
            <label class="block text-slate-400 mb-1">اسم العرض (Title)</label>
            <input type="text" value="${data.title || ""}" placeholder="Frontend Next.js" class="srv-title w-full bg-slate-800 border border-slate-700 rounded px-2.5 py-1.5 focus:outline-none">
          </div>
          <div>
            <label class="block text-slate-400 mb-1">اسم المشروع (Project)</label>
            <input type="text" value="${data.project || ""}" placeholder="my-web-app" class="srv-project w-full bg-slate-800 border border-slate-700 rounded px-2.5 py-1.5 focus:outline-none">
          </div>
          <div>
            <label class="block text-slate-400 mb-1">البورت الافتراضي (Port)</label>
            <input type="number" value="${data.default_port || data.port || 3000}" class="srv-port w-full bg-slate-800 border border-slate-700 rounded px-2.5 py-1.5 focus:outline-none font-mono">
          </div>
        </div>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-3 text-xs">
          <div>
            <label class="block text-slate-400 mb-1">مجلد التشغيل (CWD)</label>
            <input type="text" value="${data.cwd || ""}" placeholder="/path/to/project" class="srv-cwd w-full bg-slate-800 border border-slate-700 rounded px-2.5 py-1.5 focus:outline-none font-mono">
          </div>
          <div>
            <label class="block text-slate-400 mb-1">أمر التشغيل (Command)</label>
            <input type="text" value="${data.command || data.cmd || ""}" placeholder="npm run dev" class="srv-cmd w-full bg-slate-800 border border-slate-700 rounded px-2.5 py-1.5 focus:outline-none font-mono">
          </div>
        </div>
      `;
      container.appendChild(card);
    }

    function renderTargets(targets) {
      const container = document.getElementById("targetsContainer");
      container.innerHTML = "";
      const keys = Object.keys(targets);
      if (keys.length === 0) {
        container.innerHTML = `<p class="text-xs text-slate-500 py-4 text-center">لا توجد أهداف بناء معرفة حالياً. يمكنك الضغط على "إضافة هدف بناء" لإضافة هدف جديد.</p>`;
        return;
      }
      keys.forEach((k) => addTargetCard(k, targets[k]));
    }

    function addTargetCard(key = "", data = {}) {
      const container = document.getElementById("targetsContainer");
      if (container.querySelector("p")) container.innerHTML = "";
      const card = document.createElement("div");
      card.className = "target-entry bg-slate-900/90 border border-slate-700/80 rounded-xl p-4 space-y-3";
      card.innerHTML = `
        <div class="flex items-center justify-between border-b border-slate-800/80 pb-2">
          <input type="text" value="${key}" placeholder="target_key (e.g. mobile_release)" class="tgt-key font-bold text-sm bg-transparent text-amber-400 border-none focus:outline-none font-mono">
          <button onclick="this.closest('.target-entry').remove()" class="text-slate-500 hover:text-rose-400 text-xs font-semibold">x حذف</button>
        </div>
        <div class="grid grid-cols-1 md:grid-cols-3 gap-3 text-xs">
          <div>
            <label class="block text-slate-400 mb-1">اسم العرض (Title)</label>
            <input type="text" value="${data.title || data.name || ""}" placeholder="تطبيق أندرويد" class="tgt-title w-full bg-slate-800 border border-slate-700 rounded px-2.5 py-1.5 focus:outline-none">
          </div>
          <div>
            <label class="block text-slate-400 mb-1">مالك المستودع (Owner)</label>
            <input type="text" value="${data.owner || ""}" placeholder="github-username" class="tgt-owner w-full bg-slate-800 border border-slate-700 rounded px-2.5 py-1.5 focus:outline-none font-mono">
          </div>
          <div>
            <label class="block text-slate-400 mb-1">اسم المستودع (Repo)</label>
            <input type="text" value="${data.repo || ""}" placeholder="my-repo" class="tgt-repo w-full bg-slate-800 border border-slate-700 rounded px-2.5 py-1.5 focus:outline-none font-mono">
          </div>
        </div>
        <div class="grid grid-cols-1 md:grid-cols-3 gap-3 text-xs">
          <div>
            <label class="block text-slate-400 mb-1">ملف سير العمل (Workflow File)</label>
            <input type="text" value="${data.workflow || ""}" placeholder="build-apk.yml" class="tgt-wf w-full bg-slate-800 border border-slate-700 rounded px-2.5 py-1.5 focus:outline-none font-mono">
          </div>
          <div>
            <label class="block text-slate-400 mb-1">الفرع الافتراضي (Branch)</label>
            <input type="text" value="${data.branch || "main"}" placeholder="main" class="tgt-branch w-full bg-slate-800 border border-slate-700 rounded px-2.5 py-1.5 focus:outline-none font-mono">
          </div>
          <div>
            <label class="block text-slate-400 mb-1">النوع (Type)</label>
            <select class="tgt-type w-full bg-slate-800 border border-slate-700 rounded px-2.5 py-1.5 focus:outline-none text-slate-200">
              <option value="apk" ${data.type === "apk" ? "selected" : ""}>Android APK</option>
              <option value="generic" ${data.type !== "apk" ? "selected" : ""}>Generic CI/CD Workflow</option>
            </select>
          </div>
        </div>
      `;
      container.appendChild(card);
    }

    async function testTelegram() {
      const token = document.getElementById("tgToken").value.trim();
      const status = document.getElementById("tgStatus");
      status.innerText = "جاري فحص الاتصال...";
      status.className = "text-xs mt-1 text-blue-400";
      const res = await fetch("/api/test/telegram", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ token }),
      });
      const data = await res.json();
      if (data.ok) {
        status.innerText = `[OK] متصل بنجاح: ${data.name} (@${data.username}) - ID: ${data.id}`;
        status.className = "text-xs mt-1 text-emerald-400 font-semibold";
      } else {
        status.innerText = `[ERROR] فشل الاتصال: ${data.error}`;
        status.className = "text-xs mt-1 text-rose-400 font-semibold";
      }
    }

    async function detectChatId() {
      const token = document.getElementById("tgToken").value.trim();
      const status = document.getElementById("detectStatus");
      if (!token) {
        status.innerText = "[!] يرجى كتابة توكن البوت أولاً.";
        status.className = "text-xs mt-1 text-amber-400";
        return;
      }
      status.innerText = "جاري فحص الرسائل الواردة للبوت لالتقاط معرّفك...";
      status.className = "text-xs mt-1 text-blue-400";
      const res = await fetch("/api/detect/telegram_chat_id", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ token }),
      });
      const data = await res.json();
      if (data.ok) {
        document.getElementById("tgUserId").value = data.chat_id;
        status.innerText = `[OK] تم التقاط المعرّف بنجاح: ${data.name} (@${data.username}) - ID: ${data.chat_id}`;
        status.className = "text-xs mt-1 text-emerald-400 font-semibold";
      } else {
        status.innerText = `[!] ${data.error}`;
        status.className = "text-xs mt-1 text-amber-400";
      }
    }

    async function browseFolder() {
      try {
        const res = await fetch("/api/select_folder");
        const data = await res.json();
        if (data.ok && data.path) {
          const current = document.getElementById("syncBaseDir").value.trim();
          if (!current) {
            document.getElementById("syncBaseDir").value = data.path;
          } else if (!current.includes(data.path)) {
            document.getElementById("syncBaseDir").value = current + ", " + data.path;
          }
          scanCurrentRepos();
        } else {
          const manual = prompt("أدخل المسار الكامل للمجلد:", "");
          if (manual && manual.trim()) {
            const current = document.getElementById("syncBaseDir").value.trim();
            document.getElementById("syncBaseDir").value = current ? current + ", " + manual.trim() : manual.trim();
            scanCurrentRepos();
          }
        }
      } catch (err) {
        const manual = prompt("أدخل مسار المجلد:", "");
        if (manual && manual.trim()) {
          const current = document.getElementById("syncBaseDir").value.trim();
          document.getElementById("syncBaseDir").value = current ? current + ", " + manual.trim() : manual.trim();
          scanCurrentRepos();
        }
      }
    }

    async function scanCurrentRepos() {
      const raw = document.getElementById("syncBaseDir").value.trim();
      const status = document.getElementById("repoScanStatus");
      const listEl = document.getElementById("foundReposList");
      if (!raw) {
        status.innerText = "لم يتم تحديد أي مسارات للمشاريع بعد.";
        listEl.classList.add("hidden");
        return;
      }
      const paths = raw.split(",").map(s => s.trim()).filter(Boolean);
      status.innerText = "جاري فحص المسارات...";
      try {
        const res = await fetch("/api/scan/repos", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ paths }),
        });
        const data = await res.json();
        if (data.ok) {
          status.innerText = `[OK] تم العثور على ${data.count} مستودع(ات) Git في المسارات المحددة`;
          status.className = "text-xs text-emerald-400 font-mono";
          if (data.count > 0) {
            listEl.innerHTML = data.repos.map(r => `<div>• <span class="text-white font-bold">${r.name}</span> <span class="text-slate-500">(${r.branch})</span> - <span class="text-slate-400">${r.path}</span></div>`).join("");
            listEl.classList.remove("hidden");
          } else {
            listEl.classList.add("hidden");
          }
        } else {
          status.innerText = "[!] تعذر فحص المستودعات.";
          status.className = "text-xs text-rose-400 font-mono";
          listEl.classList.add("hidden");
        }
      } catch (err) {
        status.innerText = "[!] خطأ أثناء فحص المستودعات: " + err;
        status.className = "text-xs text-rose-400 font-mono";
        listEl.classList.add("hidden");
      }
    }

    async function autoDiscoverServers() {
      const raw = document.getElementById("syncBaseDir").value.trim();
      if (!raw) {
        showToast("يرجى تحديد مسار مجلد المشاريع أولاً.", true);
        return;
      }
      const paths = raw.split(",").map(s => s.trim()).filter(Boolean);
      try {
        const res = await fetch("/api/scan/servers", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ paths }),
        });
        const data = await res.json();
        if (data.ok && data.count > 0) {
          renderServers(data.servers);
          showToast(`تم اكتشاف وتجهيز ${data.count} خادم(ات) من مشاريعك بنجاح!`);
        } else {
          showToast("لم يتم العثور على ملفات خوادم قياسية (مثل package.json أو manage.py أو main.py) في المشاريع.", true);
        }
      } catch (err) {
        showToast("خطأ أثناء الاكتشاف التلقائي للخوادم: " + err, true);
      }
    }

    async function testGroq() {
      const key = document.getElementById("groqKey").value.trim();
      const status = document.getElementById("groqStatus");
      status.innerText = "جاري الفحص...";
      status.className = "text-xs mt-1 text-blue-400";
      const res = await fetch("/api/test/groq", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ key }),
      });
      const data = await res.json();
      if (data.ok) {
        status.innerText = `[OK] المفتاح صالح (${data.models_count} نموذج متوفر)`;
        status.className = "text-xs mt-1 text-emerald-400 font-semibold";
      } else {
        status.innerText = `[ERROR] خطأ في المفتاح: ${data.error}`;
        status.className = "text-xs mt-1 text-rose-400 font-semibold";
      }
    }

    async function testGithub() {
      const token = document.getElementById("ghToken").value.trim();
      const status = document.getElementById("ghStatus");
      status.innerText = "جاري الفحص...";
      status.className = "text-xs mt-1 text-blue-400";
      const res = await fetch("/api/test/github", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ token }),
      });
      const data = await res.json();
      if (data.ok) {
        status.innerText = `[OK] التوكن صالح للمستخدم: @${data.login}`;
        status.className = "text-xs mt-1 text-emerald-400 font-semibold";
      } else {
        status.innerText = `[ERROR] خطأ في التوكن: ${data.error}`;
        status.className = "text-xs mt-1 text-rose-400 font-semibold";
      }
    }

    async function saveAllConfig() {
      const env = {
        TELEGRAM_BOT_TOKEN: document.getElementById("tgToken").value.trim(),
        TELEGRAM_USER_ID: document.getElementById("tgUserId").value.trim(),
        TELEGRAM_CHAT_ID: document.getElementById("tgUserId").value.trim(),
        TELEGRAM_ADMIN_IDS: document.getElementById("tgUserId").value.trim(),
        GROQ_API_KEY: document.getElementById("groqKey").value.trim(),
        GROQ_MODEL: document.getElementById("groqModel").value,
        GITHUB_TOKEN: document.getElementById("ghToken").value.trim(),
        SYNC_BASE_DIR: document.getElementById("syncBaseDir").value.trim(),
        SYNC_IGNORED_NAMES: document.getElementById("syncIgnored").value.trim(),
        SYNC_INTERVAL_MINUTES: document.getElementById("syncInterval").value.trim(),
        SYNC_PUSH: document.getElementById("syncPush").value,
      };

      if (!env.TELEGRAM_BOT_TOKEN) {
        showToast("يرجى إدخال توكن بوت تيليجرام قبل الحفظ.", true);
        switchTab(1);
        return;
      }

      const servers = {};
      document.querySelectorAll(".server-entry").forEach((el) => {
        const k = el.querySelector(".srv-key").value.trim();
        if (k) {
          servers[k] = {
            title: el.querySelector(".srv-title").value.trim(),
            project: el.querySelector(".srv-project").value.trim(),
            default_port: parseInt(el.querySelector(".srv-port").value) || 3000,
            cwd: el.querySelector(".srv-cwd").value.trim() || ".",
            command: el.querySelector(".srv-cmd").value.trim(),
          };
        }
      });

      const targets = {};
      document.querySelectorAll(".target-entry").forEach((el) => {
        const k = el.querySelector(".tgt-key").value.trim();
        if (k) {
          targets[k] = {
            title: el.querySelector(".tgt-title").value.trim(),
            owner: el.querySelector(".tgt-owner").value.trim(),
            repo: el.querySelector(".tgt-repo").value.trim(),
            workflow: el.querySelector(".tgt-wf").value.trim(),
            branch: el.querySelector(".tgt-branch").value.trim(),
            type: el.querySelector(".tgt-type").value,
          };
        }
      });

      const prompts = {
        manager_report: document.getElementById("promptManagerReport") ? document.getElementById("promptManagerReport").value.trim() : "",
        diagnose: document.getElementById("promptDiagnose") ? document.getElementById("promptDiagnose").value.trim() : "",
        chat: document.getElementById("promptChat") ? document.getElementById("promptChat").value.trim() : "",
      };

      try {
        const res = await fetch("/api/save", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ env, servers, targets, prompts }),
        });
        const data = await res.json();
        if (data.ok) {
          showToast(data.message);
        } else {
          showToast("حدث خطأ أثناء الحفظ: " + data.error, true);
        }
      } catch (err) {
        showToast("تعذر الاتصال بالخادم: " + err, true);
      }
    }

    window.addEventListener("DOMContentLoaded", loadInitialConfig);
  </script>
</body>
</html>
"""


def run_cli_wizard():
    print("=" * 65)
    print(" [CONFIG] HorusOps | Interactive Setup Wizard (CLI)")
    print("=" * 65)
    print("اضغط Enter للموافقة على القيمة الافتراضية الموضحة بين أقواس.\n")

    current_env = parse_env_file(ENV_FILE)

    # 1. Telegram Bot Token
    def_token = current_env.get("TELEGRAM_BOT_TOKEN", "")
    prompt_token = f"1. توكن بوت تيليجرام (Telegram Bot Token) [{def_token[:10]}...]: " if def_token else "1. توكن بوت تيليجرام (Telegram Bot Token): "
    token = input(prompt_token).strip() or def_token
    while not token:
        print("[!] توكن البوت إلزامي. يرجى إنشاء بوت عبر @BotFather وإدخال التوكن.")
        token = input("توكن البوت: ").strip()

    tg_test = test_telegram_token(token)
    if tg_test.get("ok"):
        print(f"   [OK] تم التحقق من البوت: {tg_test.get('name')} (@{tg_test.get('username')})")
    else:
        print(f"   [WARN] تنبيه: {tg_test.get('error')}")

    # 2. Telegram User ID
    def_user_id = current_env.get("TELEGRAM_ADMIN_IDS", "") or current_env.get("TELEGRAM_CHAT_ID", "")
    print("\n2. معرّف تيليجرام (Telegram User/Chat ID):")
    print("   [خيار 1] افتح البوت في تيليجرام وأرسل أي رسالة (مثل /start) للالتقاط التلقائي.")
    print("   [خيار 2] أو أدخل الـ ID الخاص بك يدوياً.")
    choice = input(f"   أدخل الـ ID مباشرة، أو اضغط Enter للالتقاط التلقائي [{def_user_id}]: ").strip()

    user_id = def_user_id
    if not choice and not def_user_id:
        print("   [*] جاري فحص الرسائل الواردة للبوت لالتقاط المعرف...")
        det = detect_telegram_chat_id(token)
        if det.get("ok"):
            user_id = det["chat_id"]
            print(f"   [OK] تم التقاط المعرف بنجاح: {det.get('name')} (@{det.get('username')}) - ID: {user_id}")
        else:
            print(f"   [WARN] {det.get('error')}")
            user_id = input("   يرجى إدخال الـ ID يدوياً: ").strip()
    elif choice:
        user_id = choice

    # 3. Base Directory
    def_base = current_env.get("SYNC_BASE_DIR", str(Path.home() / "projects"))
    print(f"\n3. مسار مجلد المشاريع (Projects Base Directory) [{def_base}]:")
    base_dir_in = input("   المسار (يمكن إدخال مسارات متعددة مفصولة بفواصل): ").strip() or def_base

    paths = [p.strip() for p in base_dir_in.split(",") if p.strip()]
    found_repos = scan_repositories_in_paths(paths)
    print(f"   [OK] تم العثور على {len(found_repos)} مستودع Git في المسارات المحددة.")
    for r in found_repos[:5]:
        print(f"      - {r['name']} ({r['branch']})")
    if len(found_repos) > 5:
        print(f"      ... و {len(found_repos) - 5} مستودعاً آخر.")

    # 4. Groq Key
    def_groq = current_env.get("GROQ_API_KEY", "")
    print(f"\n4. مفتاح Groq API للتحليل والتشخيص (اختياري) [{def_groq[:8]}...]:" if def_groq else "\n4. مفتاح Groq API للتحليل والتشخيص (اختياري):")
    groq_key = input("   المفتاح (اضغط Enter للتخطي): ").strip() or def_groq
    if groq_key:
        g_test = test_groq_key(groq_key)
        if g_test.get("ok"):
            print(f"   [OK] مفتاح Groq صالح ({g_test.get('models_count')} نموذج متاح)")
        else:
            print(f"   [WARN] {g_test.get('error')}")

    # 5. GitHub Token
    def_gh = current_env.get("GITHUB_TOKEN", "")
    print(f"\n5. توكن GitHub الشخصي (اختياري) [{def_gh[:8]}...]:" if def_gh else "\n5. توكن GitHub الشخصي (اختياري):")
    gh_token = input("   التوكن (اضغط Enter للتخطي): ").strip() or def_gh
    if gh_token:
        gh_test = test_github_token(gh_token)
        if gh_test.get("ok"):
            print(f"   [OK] توكن GitHub صالح للمستخدم: @{gh_test.get('login')}")
        else:
            print(f"   [WARN] {gh_test.get('error')}")

    # Auto servers
    print("\n[*] جاري فحص المشاريع لاكتشاف الخوادم المحلية وتوليد servers.json...")
    auto_servers = auto_scan_servers_in_paths(paths)
    existing_servers = read_json_safe(SERVERS_FILE, {}).get("servers", {})
    merged_servers = {**auto_servers, **existing_servers}
    print(f"   [OK] تم تجهيز تعريفات {len(merged_servers)} خادم(ات).")

    # Save
    new_env = {
        "TELEGRAM_BOT_TOKEN": token,
        "TELEGRAM_USER_ID": user_id,
        "TELEGRAM_CHAT_ID": user_id,
        "TELEGRAM_ADMIN_IDS": user_id,
        "GROQ_API_KEY": groq_key,
        "GROQ_MODEL": current_env.get("GROQ_MODEL", "llama-3.3-70b-versatile"),
        "GITHUB_TOKEN": gh_token,
        "SYNC_BASE_DIR": base_dir_in,
        "SYNC_IGNORED_NAMES": current_env.get("SYNC_IGNORED_NAMES", "ignore,personal,archive,.git,node_modules,dist,build,.venv"),
        "SYNC_PUSH": current_env.get("SYNC_PUSH", "true"),
        "SYNC_INTERVAL_MINUTES": current_env.get("SYNC_INTERVAL_MINUTES", "30"),
    }
    write_env_file(ENV_FILE, new_env)

    with open(SERVERS_FILE, "w", encoding="utf-8") as f:
        json.dump({"servers": merged_servers}, f, ensure_ascii=False, indent=2)

    if not TARGETS_FILE.exists():
        example_targets = read_json_safe(ROOT_DIR / "targets.example.json", {"targets": {}})
        with open(TARGETS_FILE, "w", encoding="utf-8") as f:
            json.dump(example_targets, f, ensure_ascii=False, indent=2)

    print("\n" + "=" * 65)
    print(" [OK] تم حفظ التهيئة بنجاح في .env و servers.json و targets.json")
    print("=" * 65)
    print("\nيمكنك الآن تشغيل البوت مباشرة عبر:")
    print("   ./scripts/run_bot.sh\n")
    print("أو تثبيته كخدمة خلفية دائمة مع إقلاع النظام:")
    print("   ./scripts/install_launchd.sh   # macOS")
    print("   ./scripts/install_systemd.sh   # Linux\n")


def main():
    import argparse
    parser = argparse.ArgumentParser(description="HorusOps Configuration Setup Wizard")
    parser.add_argument("--port", type=int, default=8585, help="Port to run web wizard on (default: 8585)")
    parser.add_argument("--cli", "-c", action="store_true", help="Run in interactive terminal CLI mode (for VPS/headless)")
    args = parser.parse_args()

    if args.cli:
        try:
            run_cli_wizard()
        except (KeyboardInterrupt, EOFError):
            print("\n\n[INFO] تم إنهاء معالج الإعداد التفاعلي.")
        return

    port = get_free_port(args.port)
    server_address = ("127.0.0.1", port)
    httpd = http.server.ThreadingHTTPServer(server_address, SetupRequestHandler)
    httpd.daemon_threads = True
    url = f"http://localhost:{port}"

    print("=" * 65)
    print(" [CONFIG] HorusOps | Configuration Setup Wizard")
    print("=" * 65)
    print(f"\n[INFO] Web Setup running at: {url}\n")
    print("Press Ctrl+C in this terminal to stop.")
    print("=" * 65)

    try:
        webbrowser.open(url)
    except Exception:
        pass

    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        print("\nShutting down setup wizard. Goodbye!")
        httpd.server_close()


if __name__ == "__main__":
    main()
